### ISSUE TITLE
Changing API

### ISSUE THREAD

**Issue by Kavignon** [JoeMayo/LinqToTwitter#1]
I've had the chance to use this API and frankly, I found it really useful.
I then thought that it could a great iteration of your API to not only provide support for the Twitter API, but also for other major social networks : 

-Facebook

-Instagram

-Snapchat

Althought I'm asking if you're thinking it could be a good idea, what I'd propose is to increment the library and do a pull request to see if that could work for you.

Let me know what you think about this !

**Comment by JoeMayo** [comment]
?Hi Kevin,


Thanks, it's a lot of fun and I enjoy the fact that it helps people. :)  What you're proposing is a ton of work though. While sophisticated, the code isn't really hard to write, but think about all the documentation, samples, and support required. I can see where it would definitely be useful, but I have my open-source hands full with LINQ to Twitter and it's the right size that lets me continue concentrating on quality over quantity.


Regards,


Joe


________________________________

**Comment by Kavignon** [comment]
If I was to write an API, only for one of the social networks (Facebok) that I've listed, could I add it to your API?

Basically, I'd would like to build from architecture. Otherwise, if I were to build an API called LinqToFacebook, would it be an issue or something ?


Regards, 

Kevin

**Comment by JoeMayo** [comment]
?It should be a separate project named LINQ to Facebook because LINQ to Twitter already has a distinct identity. If you were to do this, I would be willing to help you get started, letting you take the lead.


Joe

________________________________

**Comment by Kavignon** [comment]
I have forked the LinqToTwitter library and renamed it LinqToSocial as I wanted also to bring support for Instagram too and maybe for others if the need was found. I hope it does not  create any issues otherwise, I'll just delete my fork and create a brand new repo.
It is so nice of you to be willing to contribute ! I accept your help!

**Comment by Kavignon** [comment]
I just understood your comment. I'll close my repo and create a brand new.
For now, the help I would need is really getting started with the Facebook API and create good data models for users so they'll be flexible enough for refactoring and enhancements for the future if and when I was to add more social networks support

**Comment by Kavignon** [comment]
@JoeMayo  I was wondering how to get started with my API. Could you give me some pointers on how to get my architecture started for the Facebook API? I'd like to use a query model like yours, but not entirely the same as I don't want to copy the work that you have done !

Thanks for the  help ! :)

**Comment by JoeMayo** [comment]
You might have noticed that I don't have much bandwidth for this right now. I'm working on LINQ to Twitter v4.0 and pretty much have my hands full.
