### ISSUE TITLE
Status.Text property 

### ISSUE THREAD

**Issue by devikprod** [JoeMayo/LinqToTwitter#100]
Good Morning.
How to get the full text content when tweet is truncated according to the new twitter APIs ( tweet_mode = extended and full_text instead of text is returned ) in query ?
Thanks in advance.

**Comment by JoeMayo** [comment]
Hi devikprod,

There's a preview version of LINQ to Twitter that supports extended tweets: https://www.nuget.org/packages/linqtotwitter/4.2.0-beta2 - You can use the FullText property. There's also an ExtendedEntities property. Here's the Twitter docs that explain the parameters: https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

**Comment by devikprod** [comment]
Hi,
It works fine, thanks.
Best Regards

**Comment by Jezvin** [comment]
Hi, 
it doesn't seem to work for me.
I do a search query : 
```
 var search = await
                    (from searchQ in ctx.Search
                     where searchQ.Type == SearchType.Search &&
                           searchQ.ResultType == ResultType.Recent &&
                           searchQ.Query == "my search" &&
                           searchQ.TweetMode == TweetMode.Extended
                     select searchQ).SingleOrDefaultAsync();
```

The TweetMode of the return search object is Extended, but the statuses are all in TweetMode=Compat
The FullText property is truncated as the Text one

Am I missing something ? Thanks

**Comment by JoeMayo** [comment]
Do you have a status ID of a tweet that you're seeing this on so I can repro?

**Comment by tobycrafted** [comment]
I think I'm getting the same behaviour here as Jezvin - I have a full text, but it is still truncated.

What am I missing?

**Comment by planeguy** [comment]
I dunno if you ever got an ID for this issue, but https://twitter.com/SaPlaneGuy/status/936318749694554112 is longer. I have the same issue

**Comment by planeguy** [comment]
I did get this to work. You need to set the TweetMode in your query to get extended text:

```
twitterCtx.Search.Where(s =>
                            s.Type == SearchType.Search
                            && s.Query == twitterTag
                            && s.SinceID == sinceID
                            && s.MaxID == maxId
                            && s.ResultType == ResultType.Recent
                            && s.TweetMode == TweetMode.Extended //you need this
```

**Comment by rkamaladasa** [comment]
.TweetMode == TweetMode.Extended no longer works. :(
