### ISSUE TITLE
Problem with getting email address

### ISSUE THREAD

**Issue by devwheel** [JoeMayo/LinqToTwitter#102]
I'm trying to automate my asp.net account creation process after signing in with twitter.  I've followed the sample by bigbrainentelligence.  In my code, I always get "my" twitter user back vs the user that just logged in.

After I get a valid loginInfo, I call this function.  Stepping through in debug always returns my twitter acocount.  

Any ideas or is this a bug?

        public async static Task<LinqToTwitter.User> GetTwitterUser(ExternalLoginInfo loginInfo)
        {
            string clientid = ConfigurationManager.AppSettings.Get("id:twitterclientid");
            string clientsecret = ConfigurationManager.AppSettings.Get("id:twitterclientsecret");
            string accesstoken = ConfigurationManager.AppSettings.Get("id:twitteraccesstoken");
            string tokensecret = ConfigurationManager.AppSettings.Get("id:twittertokensecret");

            try
            {
                var authTwitter = new SingleUserAuthorizer
                {
                    CredentialStore = new SingleUserInMemoryCredentialStore
                    {
                        ConsumerKey = clientid,
                        ConsumerSecret = clientsecret,
                        OAuthToken = accesstoken,
                        OAuthTokenSecret = tokensecret,
                        UserID = ulong.Parse(loginInfo.Login.ProviderKey),
                        ScreenName = loginInfo.DefaultUserName
                    }
                };

                await authTwitter.AuthorizeAsync();

                var twitterCtx = new TwitterContext(authTwitter);
                var verifyResponse =
                      await (from acct in twitterCtx.Account
                            where (acct.Type == AccountType.VerifyCredentials) && (acct.IncludeEmail == true)
                            select acct)
                            .SingleOrDefaultAsync();

                if (verifyResponse != null && verifyResponse.User != null)
                {
                    User twitterUser = verifyResponse.User;
                    //assign email to existing authentication object
                    loginInfo.Email = twitterUser.Email;
                   return twitterUser;

                }
                return null;
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
                return null;
            }
        }

**Comment by JoeMayo** [comment]
It looks like you're using a SingleUserAuthorizer with all four credentials, which means that the user isn't authorizing your app. Most likely, the TwitterAccessToken and TwitterTokenSecret are yours, meaning that you're operating on your own account. You need to use one of the other authorizers that force the user to log in (https://github.com/JoeMayo/LinqToTwitter/wiki/Learning-to-use-OAuth). Once the user authorizes your app, save their credentials so they don't have to authorize every time and when the user comes back, if you know who they are, reload their credentials and not yours.

**Comment by devwheel** [comment]
So I'm using this as part of a Asp.Net web application where the user is authenticating with twitter already to get to the code where I call the function.  The userid and screenname are taken from the twitter authentication provider after they consent.  I'm I still looking the wrong way?

**Comment by JoeMayo** [comment]
Your code looks like it's reading the user credentials from your config file:

        string accesstoken = ConfigurationManager.AppSettings.Get("id:twitteraccesstoken");
        string tokensecret = ConfigurationManager.AppSettings.Get("id:twittertokensecret");

Check out how the demo gets these tokens:

            // This is how you access credentials after authorization.
            // The oauthToken and oauthTokenSecret do not expire.
            // You can use the userID to associate the credentials with the user.
            // You can save credentials any way you want - database, isolated storage, etc. - it's up to you.
            // You can retrieve and load all 4 credentials on subsequent queries to avoid the need to re-authorize.
            // When you've loaded all 4 credentials, LINQ to Twitter will let you make queries without re-authorizing.
            //
            //var credentials = auth.CredentialStore;
            //string oauthToken = credentials.OAuthToken;
            //string oauthTokenSecret = credentials.OAuthTokenSecret;
            //string screenName = credentials.ScreenName;
            //ulong userID = credentials.UserID;
            //

There are Web Forms and MVC demos in the Samples folder, here's the MVC demo: https://github.com/JoeMayo/LinqToTwitter/blob/master/Samples/net46/CSharp/AspNetSamples/MvcDemo/Controllers/OAuthController.cs
