### ISSUE TITLE
Update an Update

### ISSUE THREAD

**Issue by EmptyCoffin** [JoeMayo/LinqToTwitter#103]
How would you update a update tweet's text when you have the status id?
i.e. "Tweet To Be Changed" => "Tweet Has Been Changed"

**Comment by JoeMayo** [comment]
That feature isn't a part of the Twitter API, so LINQ to Twitter won't have it either. It seems like a popular request though.

**Comment by EmptyCoffin** [comment]
Thanks for the quick response
