### ISSUE TITLE
How to give additional permissions request email addresses from our app users

### ISSUE THREAD

**Issue by citymapia** [JoeMayo/LinqToTwitter#104]
For getting our App users  email, I used this code.
   var verifyResponse =
                await
                    (from acct in twitterCtx.Account
                     where acct.Type == AccountType.VerifyCredentials && acct.IncludeEmail == true
                     select acct)
                    .SingleOrDefaultAsync();
but the verifyResponse  returns only  app owner details with email.not the users email. This my full code.What is wrong with this.please help.
 var authTwitter = new SingleUserAuthorizer
                    {
                        CredentialStore = new SingleUserInMemoryCredentialStore
                        {
                            ConsumerKey = app_ConsumerKey ,
                            ConsumerSecret =app_ConsumerSecret ,
                            OAuthToken =app_OAuthToken ,
                            OAuthTokenSecret =app_OAuthTokenSecret ,
                            UserID = loginedUser_ProviderKey,
                            ScreenName = loginedUser_DefaultUserName
                        }
                    };

await authTwitter.AuthorizeAsync();
var twitterCtx = new TwitterContext(authTwitter);
                    var verifyResponse =
                await
                    (from acct in twitterCtx.Account
                     where acct.Type == AccountType.VerifyCredentials && acct.IncludeEmail == true
                     select acct)
                    .SingleOrDefaultAsync();

This verify response returns app owner details.not current logined user.

**Comment by JoeMayo** [comment]
Did you verify that OAuthToken and OAuthTokenSecret are the ones returned when the user authorizes, rather than belonging to your app?
