### ISSUE TITLE
get specific user likes

### ISSUE THREAD

**Issue by SignCube** [JoeMayo/LinqToTwitter#105]
hi 
how can i get tweets that i liked it  and tweets that i retweeted ?

tnx so much

**Comment by JoeMayo** [comment]
Hi,

The [ConsoleSamples ](https://github.com/JoeMayo/LinqToTwitter/tree/master/Samples/net46/CSharp/ConsoleSamples)have demos on all of the API calls and the [Wiki ](https://github.com/JoeMayo/LinqToTwitter/wiki)has documentation.

[@JoeMayo](https://twitter.com/JoeMayo)
