### ISSUE TITLE
Multiple Search Query Topics

### ISSUE THREAD

**Issue by johnwmcintosh** [JoeMayo/LinqToTwitter#106]
I want to do a SearchType.Search for multiple Query strings. For example "flying" and "swimming". These would be provided by a user at runtime.

I used the Albhari [PredicateBuilder](http://www.albahari.com/nutshell/predicatebuilder.aspx) and Nested Predicates pattern for doing this.  

When I search for only one term, e.g. "flying", it works fine. When I try more than one term, e.g. '"flying" or "swimming"', it throws a "**An item with the same key has already been added**" exception.

```
var terms = new List<string>() { "flying" , "swimming" }; // <<-- causes exception
// var terms = new List<string>() { "flying" }; // <<-- works

var queryPredicate = PredicateBuilder.False<Search>();
foreach (var term in terms)
{
    string ter = term;
    queryPredicate = queryPredicate.Or(t => t.Query == ter);
}

var typePredicate = PredicateBuilder.True<Search>();
typePredicate = typePredicate.And(t => t.Type == SearchType.Search);
typePredicate = typePredicate.And(queryPredicate);

foreach
(
    var search in Context.Search.Where(typePredicate).ToList() // <<-- Exception here
)
{
    // iterate through Statuses
}
```

I can't figure out why LinqToTwitter throws the error. How else can I query for more than one term?

**Comment by JoeMayo** [comment]
I'm not familiar with PredicateBuilder. From the error message, it sounds like the code is try to add the Query parameter twice. However, you should be able to set Query one time to "flying OR swimming". You can try out a query on https://twitter.com/search-home and click on the operators link to learn what you can put in the Query parameter.
