### ISSUE TITLE
Retweets Doesnt Give Media !

### ISSUE THREAD

**Issue by SignCube** [JoeMayo/LinqToTwitter#107]
Hi 
When I Retweet A Post With Image And Get My Tweet And Retweet With LinqtoTwitter There Is no MediaEntities . 

But In Direct Tweets It Works correctly

Whats The Problem ?

**Comment by SignCube** [comment]
can u help me please ?

**Comment by kunal-lwt** [comment]
Seems like a bug/feature. I also tried using the filter:media to get only those tweets which have media, so I also got the same issue. The best way I tried resolve it is, firstly implement my direct search and then filter the tweets on the basis of Text. 

1. If ReplyTo field is null, meaning it's a **Reply**
2. If Text starts with 'RT ', then it's a retweet
3. If MediaEntity.Count > 0, then fetch it's Display and tweet URL.

**Comment by JoeMayo** [comment]
@SignCube SignCube,

Can you show me the status ID of a tweet that you're seeing this on? Did @kharasoft  response help?

I'm using v4.2.0-beta3 and am seeing both Entities and ExtendedEntities populated for both the original and retweet.

Joe
