### ISSUE TITLE
TweetMode missing in Core Version?

### ISSUE THREAD

**Issue by maximilianbaumann** [JoeMayo/LinqToTwitter#108]
Hey,

im using the 4.2.0-beta2 of your library in both a command line application and an ASP.NET Core application.
In both apps im using the following code, with "tweitterUserId and "since" beeing passed in arguments:

`var listTweets = (from tweet in context.Status
                              where tweet.Count == 200
                                    && tweet.Type == StatusType.User
                                    && tweet.TweetMode == TweetMode.Extended
                                    && tweet.ExcludeReplies == true
                                    && tweet.ScreenName == twitterUserId
                                    && tweet.CreatedAt > since
                              select tweet
                              ).ToList();`

The command line app does compile and give me the expected results.
Whereas the ASP.NET Core app won't compile and throws the following error:

> 'Status' does not contain a definition for 'TweetMode' and no extension method 'TweetMode' accepting a first argument of type 'Status' could be found (are you missing a using directive or an assembly reference?)

When I "Go To Definition" (pressing F12) on Satus the displayed Code doesn't contain a propperty TweetMode in the linqtotwitter.core.dll, whereas it's present in linqtotwitter.net.dll .
Is the linqtotwitter.core.dll somehow missing the TweetMode propperty on Status?
Or am I just doing something blatantly wrong?

Thanks in advance for your help

**Comment by JoeMayo** [comment]
Does upgrading to ASP.NET Core v2.0 help?
