### ISSUE TITLE
Wrong version on nuget

### ISSUE THREAD

**Issue by giorgiozanoli** [JoeMayo/LinqToTwitter#109]
Dear JoeMayo,
         I tried to install your lib from nuget package manager, but the version that the pm installs is different from your current master.
The missing feature I found is that the Status class doesn't have the FullText and ExtendedTweet properties, so when retrieving tweets it's impossible to obtail the long version of the text.

Kind regards.

Keep up the good work!

Giorgio

**Comment by JoeMayo** [comment]
Hi Giorgio,

Which version are you using. I have a 4.2.0-beta3 version that you will be able to see by checking pre-release.

Joe
