### ISSUE TITLE
How to get tweet sentiment on tweet search?

### ISSUE THREAD

**Issue by kunal-lwt** [JoeMayo/LinqToTwitter#110]
https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/basic-operators defines refining of API on positive or negative sentiment of a tweet by adding :) or :( in the search query. Is it possible to detect the same using LinqToTwitter?

**Comment by JoeMayo** [comment]
Yes, add :) or :( to the Query property:

            string searchTerm = "\"LINQ to Twitter\" OR Linq2Twitter OR LinqToTwitter OR JoeMayo :)";

            Search searchResponse =
                await
                (from search in twitterCtx.Search
                 where search.Type == SearchType.Search &&
                       search.Query == searchTerm &&
                       search.IncludeEntities == true &&
                       search.TweetMode == TweetMode.Extended
                 select search)
                .SingleOrDefaultAsync();
