### ISSUE TITLE
+140 truncated and QuotedStatus without User

### ISSUE THREAD

**Issue by elmeerr** [JoeMayo/LinqToTwitter#112]
Is there a way to show the now 280 characters tweets?? I've tried the "extended" mode but does not work, instead I've got empty results. I can't find this on wiki and I'm getting truncated (to 140) tweets.

Also, I noticed that when the `IsQuotedStatus `is true, sometimes the `User `of `QuotedStatus `is null...is that correct behavior?

Thanks in advance

**Comment by JoeMayo** [comment]
For TweetMode.Extended, the tweet appears in the FullText property.

**Comment by elmeerr** [comment]
Thanks, Joe!
