### ISSUE TITLE
twitterCtx.Account Error

### ISSUE THREAD

**Issue by Csirme** [JoeMayo/LinqToTwitter#113]
`
       var twitterCtx = new TwitterContext(authorizer);
                var verifyResponse =(from acct in twitterCtx.Account
                                    where acct.Type == AccountType.VerifyCredentials
                                    select acct)
                                    .SingleOrDefaultAsync();
`

 error CS1936: Could not find an implementation of the query pattern for source type 'TwitterQueryable<Account>'.  'Where' not found.
`

**Comment by Csirme** [comment]
![225](https://user-images.githubusercontent.com/16202890/35133219-f80dac94-fd09-11e7-8681-1a45efac4546.png)

**Comment by JoeMayo** [comment]
Does it help if you add the namespace declaration?:

    using System.Linq;
