### ISSUE TITLE
Links on Status

### ISSUE THREAD

**Issue by elmeerr** [JoeMayo/LinqToTwitter#115]
Hi Joe,
Is it possible (in a cleaner way) to avoid media and quoted links on status texts? The thing is I'm creating a layout where  I show the images and quoted retweets like twitter web (I'm working with WPF) there's no need to have those links on the "main" status.
I thought about using the Entities/Extended Entities to get Start/End position of the medias/quoted status links and remove from the "main status" but this would be really trick...thats why I wanna know if theres a "cleaner way" of doing this.

Regards,
Elmer

**Comment by JoeMayo** [comment]
I think you're going in the right direction, using Entities.
