### ISSUE TITLE
Status ID not being set?

### ISSUE THREAD

**Issue by RobbyRobbyRobby** [JoeMayo/LinqToTwitter#116]
Hi,

Correct me if I am wrong, but it looks like the ID of a Status (the tweet ID) is never getting set.

I found this as I was getting a list of the users status' (their timeline) and wanted to get the next x number of rows using the SinceID parameter.  But as the ID of every status is always 0 it returns the same rows over and over again.

I had a look in Status.cs and could not see the ID field getting set.

**Comment by JoeMayo** [comment]
Hi,

Did you look in the StatusID property. A lot of queries use ID as the input, so LINQ to Twitter uses StatusID to show what the ID is in Twitter, rather than the input from the code.

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by RobbyRobbyRobby** [comment]
Hi @JoeMayo 

Thank you for your fast response!

Yes, I took a look at the StatusID and that has an ID (which I presume belongs to the tweet).

However if I try to page the status query using the SinceID parameter, will it compare against the ID (which is empty).  If this is the case then the SinceID parameter will also need to be compared to the StatusID.

Does that make sense?

Thanks!
Rob

**Comment by RobbyRobbyRobby** [comment]
Update; I have it figured out.

For anyone else; Yes.  You the StatusID field is the Tweet ID in Status objects.  The ID is always 0.

You can then use MaxID and SinceID using this value.

Thanks again,
Rob.
