### ISSUE TITLE
TweetMode.Extended not supported for TwitterContext.Favorites?

### ISSUE THREAD

**Issue by BryanWilhite** [JoeMayo/LinqToTwitter#117]
I currently assume that this query will always return `0` records:

```c#
public static IEnumerable<Favorites> ToFavorites(this TwitterContext context, int count, bool includeEntities)
{
    if (context == null) return Enumerable.Empty<Favorites>();

    return context
        .Favorites
        .Where(i =>
            (i.Type == FavoritesType.Favorites) &&
            (i.Count == count) &&
            (i.IncludeEntities == includeEntities)) &&
            (i.TweetMode == TweetMode.Extended)
        .ToArray();
}

```

I assume this is because `(i.TweetMode == TweetMode.Extended)` does not work on the Twitter API itself for Favorites (Likes). I assume that I need to make two API calls to get the Status IDs of Favorites then pass batches of them to a query like this:

```c#
var query = context.Status.Where(i =>
    (i.Type == StatusType.Lookup) &&
    (i.TweetMode == TweetMode.Extended) &&
    (i.IncludeEntities == true) &&
    (i.TweetIDs == statusIds));

var statuses = query.ToArray();
```

where `statusIds` is a comma-separated list of Status IDs.

Are my assumptions in the ballpark?

**Comment by JoeMayo** [comment]
For right now, your observation is correct for current behavior. I did some research tonight and, though not explicitly documented, the initial guidance implies that `tweet_mode` should work, so I'll have to try that.

**Comment by BryanWilhite** [comment]
I appreciate you taking the time to look into this! I have been concerned that the new premium API might conceal this functionality.

**Comment by JoeMayo** [comment]
That worked! I've checked in code that lets you set i.TweetMode = TweetMode.Extended on Favorites. I'll try to get a new release on NuGet in the next couple of days. It'll still be beta (pre-release because I have some other work I'm still doing).

**Comment by BryanWilhite** [comment]
That's great! Great turnaround!

**Comment by JoeMayo** [comment]
This is now available as a NuGet download: http://bit.ly/2psNzPT

**Comment by BryanWilhite** [comment]
[Works](https://github.com/BryanWilhite/Songhay.Social/blob/master/Songhay.Social.ModelContext/Extensions/TwitterContextExtensions.cs#L20) great!
