### ISSUE TITLE
Nuget package + linux = problem

### ISSUE THREAD

**Issue by RalphBariz** [JoeMayo/LinqToTwitter#12]
The reason is, that the project reference contains the package path as "LinqToTwitter" but the real path is "linqtotwitter". Since linux paths are case sensitive, this is a problem.

BR
Ralph

**Comment by JoeMayo** [comment]
Hi Ralph,

Thanks, I've heard something about this but never understood what the real issue was. I'm working on the next version of LINQ to Twitter and will fix the NuGet package.

Joe

**Comment by RalphBariz** [comment]
Hi Joe,

Thanks, I need to tell you, that google thinks, the mail sent when you posted this, was a pishing attack. well it was not, but since github for sure was not the trigger... I fear your name may got misused. Do not know what to do about, you may figure it out I hope.

**Comment by JoeMayo** [comment]
Ralph,

I just published Beta 1 of LINQ to Twitter to NuGet. I normally don't develop on Linux - what IDE are you using on Linux? If you try this, let me know how it works for you.

Joe

**Comment by JoeMayo** [comment]
This should be fixed in v4.0: https://github.com/JoeMayo/LinqToTwitter/releases/tag/v4.0.0
