### ISSUE TITLE
"media type unrecognized." issue with xamarin IOS version 4.2.1

### ISSUE THREAD

**Issue by zalavaz1101** [JoeMayo/LinqToTwitter#120]
Hi, Could you please give some insight of what's possibly happening?. I implemented the following code using LinqToTwitter version 4.2.1:

using (var ctx = new TwitterContext(auth))
{
    Media image = await ctx.UploadMediaAsync(file, "image/png", "tweet_image");
    Status tweet = await ctx.TweetAsync(TweetText, new ulong[] { image.MediaID });
    if (tweet != null)
            Debug.WriteLine($"Tweet enviado: {tweet.Text}");
 }

Which is basically the tutorial's code. Apparently It works on the Android project of my solution, but It fails on the IOS project. I also tested the same file byte array on a Facebook Post (using Xamarin Auth only) and works on both platforms, so It seems to me an IOS problem with Twitter only.
The following error raises when I try to upload a .PNG image:

{LinqToTwitter.TwitterQueryException: {"request":"\/1.1\/media\/upload.json","error":"media type unrecognized."}

Thanks in advance. Regards

**Comment by alec-netsphere** [comment]
I have the same issue.  Error received is "media type unrecognized.", code is as follows:

            const string mediaType = "image/jpg";
            const string mediaCategory = "tweet_image";

            byte[] mediaBytes;
            
            using (var webClient = new WebClient())
            {
                mediaBytes = webClient.DownloadData(url);
            }

            var twitterContext = new TwitterContext(new SingleUserAuthorizer(...));
            
            var media = await twitterContext.UploadMediaAsync(mediaBytes, mediaType, mediaCategory);

**Comment by alec-netsphere** [comment]
I have a project which uses v3.1.2 in which UploadMediaAsync did not require either media type or media category parameters, and this works.  The error I'm seeing is in 4.2.1 which does require the parameters and doesn't work.

**Comment by alec-netsphere** [comment]
I have resolved the issue for me, which was that I was passing a page URI rather than an image SRC to the function, so in other words the byte[] I was using in UploadMediaAsync was not a representation of an image, but of a web page.
