### ISSUE TITLE
TweetAsync fails with certain symbols in particular: = and !

### ISSUE THREAD

**Issue by RyanTonerCode** [JoeMayo/LinqToTwitter#124]
var auth = new SingleUserAuthorizer
            {

                CredentialStore = new SingleUserInMemoryCredentialStore()
                {
                    ConsumerKey = AppConstants.ConsumerKey,
                    ConsumerSecret = AppConstants.ConsumerSecret,
                    AccessToken = UserViewModel.CurrentUser.oauth_token,
                    AccessTokenSecret = UserViewModel.CurrentUser.oauth_token_secret,
                
                }
            };
        await auth.AuthorizeAsync();
        var ctx = new TwitterContext(auth);

-------------------------------------------------

`var tweet = await ctx.TweetAsync("test!");`
`var tweet = await ctx.TweetAsync("test=");`

Both of the above fail; however, below works perfectly:

`var tweet = await ctx.TweetAsync("test");`

I'm not sure why those symbols fail. Could it be a way to inhibit SQL injection? If so, please add to the documentation. Thanks! I hope this information is useful, please let me know if more context is needed to help debug the issue.

**Comment by JoeMayo** [comment]
Closing - I wasn't ever able to reproduce. I'm currently using v5.0.
