### ISSUE TITLE
UpdateAccountImageAsync Bad Request

### ISSUE THREAD

**Issue by cybersea54** [JoeMayo/LinqToTwitter#127]
When i'm trying to update account profile image there is an exception:

LinqToTwitter.TwitterQueryException: "image parameter is missing."
ReasonPhrase	"Bad Request"
StackTrace	"   in LinqToTwitter.Net.TwitterErrorHandler.BuildAndThrowTwitterQueryException(String responseStr, HttpResponseMessage msg)"

```
public async Task UpdateProfile(FileInfo avatar)
{
      byte[] imageBytes = File.ReadAllBytes(avatar.FullName);
      await _twitterCtx.UpdateAccountImageAsync(imageBytes, avatar.Name, "jpg", false);
}
```

Filename is correct and imageBytes has data. Using latest version available (4.2.1).

**Comment by JoeMayo** [comment]
Sorry, it's been a while before responding. Is this still giving you problems? Does the demo code work for you?

**Comment by JoeMayo** [comment]
Thanks for reporting - I can reproduce the problem and am looking at it.

**Comment by JoeMayo** [comment]
Updates pushed to NuGet: https://www.nuget.org/packages/linqtotwitter/5.0.0-beta3
