### ISSUE TITLE
Twitter "Could not authenticate you" when session is cleared

### ISSUE THREAD

**Issue by ethan-agencyQ** [JoeMayo/LinqToTwitter#128]
Hi, I am new to this twitter world. And recently I am creating an app with LinqToTwitter. I am using the MvcAuthorizer to get the user token, it works the first time user authorizes, however, every time when I change a browser, Twitter would give me "Could not authenticate you" error at `await auth.BeginAuthorizationAsync(new Uri(callback));`. I will have to resave my app setting at https://apps.twitter.com to make it work again.

So it seems user cannot authorize my app twice, and I should always store the tokens somewhere. However, my site doesn't have a login function, the best I can do is to store session in DB, but what if the user clears the browser cookie or uses a different browser/device? How can I get a token then, is there a way to reauthenticate or reauthorize?

**Comment by ethan-agencyQ** [comment]
Strange, something must have changed outside of my app over the weekend. I did the same tests first thing today with no code modification. and everything is fine, the user can log in to the app multiple times on different devices or browsers. The Twitter is showing me "redirecting to your app" screen instead of letting the user re-authorize. Maybe Twitter just needs time to properly set up new apps.

**Comment by JoeMayo** [comment]
Thanks for following up.
