### ISSUE TITLE
Cannot reply using StatusID

### ISSUE THREAD

**Issue by maanigurad** [JoeMayo/LinqToTwitter#129]
Hi There, When I want to reply to a tweet using statusID it shows a new tweet on my account not the user account and does not reply anything on the other user's tweet. however, I can reply to my own tweet why is that!??

**Comment by JoeMayo** [comment]
Did my reply on Twitter help? https://twitter.com/maaniguard/status/1000295032186957824

**Comment by maanigurad** [comment]
Thanks Joe, yeah that did the job!
