### ISSUE TITLE
Dependencies Packages not supported by .Net Core

### ISSUE THREAD

**Issue by SamKO91** [JoeMayo/LinqToTwitter#130]
Warning	NU1701:	Package 'Microsoft.Bcl 1.1.10' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.	

To reproduce:
#1 Create a new .Net Core Class Library
#2 Add LinqToTwitter using NuGet

I'm using .net Core SDK 2.1 but same happens if i create a new Class Library with .Net Core 2.0
 @[http://prntscr.com/jrkztz](http://prntscr.com/jrkztz)

**Comment by JoeMayo** [comment]
I have a v5.0 beta available - https://www.nuget.org/packages/linqtotwitter/5.0.0-beta3 - does that help?

**Comment by SamKO91** [comment]
@JoeMayo Yes, that one worked great ;). Thanks!
