### ISSUE TITLE
Get preview image from tweet

### ISSUE THREAD

**Issue by Fr4gger** [JoeMayo/LinqToTwitter#131]
Hello,

First wanted to thank you for the effort you've placed developing this library; it's really been helpful. But now I would like to ask for your help.

I'm trying to get a preview of the embedded media of a tweet (just like in the twitter web page where it shows an image of the video, photo, GIF, or url inside). I managed to make it work only with the tweets that actually have content attached through the media entities. But how can I get an image preview of the media content for the tweets that have embedded url?

What I currently have is this:

![screen shot 2018-06-06 at 4 39 20 pm](https://user-images.githubusercontent.com/15266115/41066711-6beff094-69a8-11e8-9295-d4d5b78c030c.png)

And what I need is the picture url for the preview like this:

![screen shot 2018-06-06 at 4 39 33 pm](https://user-images.githubusercontent.com/15266115/41066726-7c3d5c16-69a8-11e8-912f-fe7b3a037bac.png)

Is there a way to get an image preview for each tweet through the LINQ to Twitter library?

Thanks in advance for your time.

**Comment by JoeMayo** [comment]
What query were you using? Here are some tips for getting a sized image:

You can size the image by suffixing the MediaEntity.MediaUrlHttps with one of the values from the Sizes collection property with this pattern:

    https://<URL>.jpg:size

Notice the colon separating the file name extension from the size. For the tweet above, you could do:

   https://pbs.twimg.com/media/Bm54nBCCYAACwBi.jpg:medium

for a medim sized tweet.

**Comment by nawidy** [comment]
@Fr4gger do you by chance use the Ads API to generate the preview? If not, what do you use to create the preview?

**Comment by JoeMayo** [comment]
Does the beta work for you? https://www.nuget.org/packages/linqtotwitter/5.0.0-beta3

**Comment by Fr4gger** [comment]
Hey @nawidy sorry for late reply. I am not sure what the Ads API is, so I don't think I am using it. What I am doing is using the media entities returned in LinqToTwitter to show a preview image of the tweet, but this only works when media (images, videos, etc.) are really attached and are not just embedded URLs. 

And @JoeMayo I will try this new beta release to see if I can get the preview from embedded URLs. Could you please tell me if you implemented a new feature that I could test? Or is it the same via the media entities? 

Thanks again for all the support getting this issue resolved.

**Comment by Fr4gger** [comment]
@JoeMayo Sorry for taking too long in testing the 5.0.0-beta3, got sidetracked with some work. I just tried using the same query, making sure that the tweets created contain attached images or media, but it still returns the media entities empty.

**Comment by Fr4gger** [comment]
@JoeMayo never mind. I just tried the beta version and it worked. I needed to update some nugget dependencies and also add the configs below to the query and it worked. Thanks a lot for your patience and help. Keep the up the good work with all your libraries.

```
tweet.Mode = Tweet.Extended
tweet.IncludeEntities = true
```

**Comment by JoeMayo** [comment]
Awesome - thanks for following up!

Joe

**Comment by nawidy** [comment]
@Fr4gger can you please share your full query, I'm unable to see a result show up. I am trying to ensure I can gather the preview for a link

This is what I currently have:
```
queriedTweets = await 
                    (
                        from tweet in TwitterContext.Status
                        where tweet.Type == StatusType.Lookup &&
                              tweet.TweetIDs == queryString &&
                              tweet.TweetMode == TweetMode.Extended &&
                              tweet.IncludeEntities == true
                        select tweet
                    ).ToListAsync();
```

@JoeMayo thanks for your hard work on this, is the ability to get an associated mediaURL for link previews not currently supported? I am unable to extract the contents of this: https://twitter.com/NawidNawidy/status/1061427542165381120

**Comment by Fr4gger** [comment]
@nawidy sorry for taking long in replying. The full query I used is this one:

 ```
var tweets = await (
                        from tweet
                        in ctx.Status
                        where tweet.Type == StatusType.User
                            && tweet.ScreenName == socialMedia.twt_screen_name
                            && tweet.IncludeEntities == true
                            && tweet.TweetMode == TweetMode.Extended
                            && tweet.IncludeRetweets == false
                            && tweet.Count == 30
                        select tweet
                    ).ToListAsync();
```

But it only works if the tweet has media entities attached to it. As far as I tried, I couldn't make a preview from a link URL, only present the attached media. I am not completely sure but I think the plugin does not support link previews, but will wait for @JoeMayo's response of your question. It would be great though for link previews to be supported. Hope the query helps you.

**Comment by nawidy** [comment]
@JoeMayo hopefully you've seen this, since I'm unable to reopen this I may need to create a new ticket for this same issue.
Thanks,
-Nawid
