### ISSUE TITLE
Retweet status

### ISSUE THREAD

**Issue by nawidy** [JoeMayo/LinqToTwitter#133]
Hi all,
It seems that when checking if a property was retweeted it is always stated as false, even with my test tweet that is retweeted. I've tried to retweet with a commend and without and they all show as false. I'm using Beta3.

var queriedTweets = await(
                from tweet
                in TwitterContext.Status
                where tweet.Type == StatusType.User
                    && tweet.ScreenName == screenName
                    && tweet.Count == 10 
                    && tweet.TweetMode == TweetMode.Extended
                    && tweet.Retweeted == false
                select tweet
            ).ToListAsync();

**Comment by JoeMayo** [comment]
It seems that Twitter sets that to false all the time, even when there's a retweet and LINQ to Twitter is copying what the Twitter API sends. LINQ to Twitter assigns an empty Status to RetweetedStatus and you can check any of the normal fields, e.g. Text, there for null as a work-around. I'll make this an issue to explicitly check inside of LINQ to Twitter whether there's a retweet and set Retweeted if there really is a retweet.

**Comment by nawidy** [comment]
Awesome thanks for all you've done thus far @JoeMayo!

**Comment by JoeMayo** [comment]
Just checked this in.

**Comment by nawidy** [comment]
Thanks @JoeMayo!
When can we expect this to be added to an updated nuget package for xamarin?

**Comment by nawidy** [comment]
@JoeMayo can we get an updated beta nuget package for 5.0 with this fix in?

**Comment by JoeMayo** [comment]
Thanks for the reminder - planning on getting a release out this week.
