### ISSUE TITLE
Ads API support - Tweet Preview

### ISSUE THREAD

**Issue by nawidy** [JoeMayo/LinqToTwitter#134]
Hi All,
I'm wondering if there will be any support/plans for the Ads-API. In particular my goal is to utilize the Ads-API to generate a preview of my tweet before posting it using:
GET accounts/:account_id/tweet/preview
https://ads-api.twitter.com/3/accounts/:account_id/tweet/preview

https://developer.twitter.com/en/docs/ads/creatives/api-reference/tweets

Thanks in advance!
-Nawid

**Comment by JoeMayo** [comment]
Maybe in the future - though not right away. I'm currently working on some of the new activity/dm apis. That said, there are the [Raw Queries and Commands](https://github.com/JoeMayo/LinqToTwitter/wiki/Safety-Hatch) that support flexible addition of new Twitter APIs before LINQ to Twitter formally implements them.

**Comment by JoeMayo** [comment]
Closing - currently making plans to support the upcoming new version of the Twitter API and will look at this at that time.
