### ISSUE TITLE
Support DELETE as a Raw command

### ISSUE THREAD

**Issue by remcodejongh** [JoeMayo/LinqToTwitter#136]
Hi,
I would like to remove subscriptions from my accounty activity webhook. I'd like to use the `ExecuteRawAsync` method, however that only supports POST methods right now. Is it possible to introduce some sort of method overload where the HttpMethod can be provided?

If not, can you provide a schedule for when this will be supported by the TwitterContext?

Thanks in advance!

**Comment by JoeMayo** [comment]
Hi,

Good idea - I'll add it as a new task. I have quite a queue of tasks and it's hard to tell when I'd be able to do it myself. If you or anyone else are up to the challenge, I'd be happy to accept a pull request (with unit tests).

(@JoeMayo)[https://twitter.com/JoeMayo]

**Comment by JoeMayo** [comment]
Added overload to `ExecuteRawQueryAsync` that takes a `HttpMethod` parameter.
