### ISSUE TITLE
direct_messages/events: One good example???

### ISSUE THREAD

**Issue by ahmad-atallah** [JoeMayo/LinqToTwitter#137]
I've been told that LinqToTwitter is updated to include the twitter new API for direct_messages/events.
Though, for hours of searching and googling I couldn't find one good (ASP .Net C#) example of using LinqToTwitter (starting from the beginning).

So I have my twitter app 4 keys (consumerKey, consumerSecret, accessToken, accessTokenSecret), now what do I do?!

**Comment by JoeMayo** [comment]
Documented in [Working with Direct Messages](https://github.com/JoeMayo/LinqToTwitter/wiki/Working-with-Direct-Messages).
