### ISSUE TITLE
Error when replicating .Net Xamarin version, getting package errors in native projects 

### ISSUE THREAD

**Issue by jordan-hewitt** [JoeMayo/LinqToTwitter#138]
I have copied the code for implementing the ApplicationOnlyAuthorizer using Dependency Injection like it is in the example and I am getting the following error:

Error CS0012: The type 'IAuthorizer' is defined in an assembly that is not referenced. You must add a reference to assembly 'LinqToTwitter.net, Version=4.2.1.41313, Culture=neutral, PublicKeyToken=957107be965c25d9'. (CS0012) (TweetSafe.iOS)

This is happening when I try to run either the Android and iOS version.  I am referencing the package LinqToTwitter in all files (works fine in PCL but throwing errors in Android an iOS) and have downloaded the most recent version of the package.  

The "quick fix" option tells me to reference  'LinqToTwitter.net, Version=4.2.1.41313, Culture=neutral, PublicKeyToken=957107be965c25d9' in which I am not sure where this would be.  But when I do the quick fix, it does nothing.

**Comment by jordan-hewitt** [comment]
PCL file

<img width="468" alt="screen shot 2018-08-01 at 11 50 23 am" src="https://user-images.githubusercontent.com/16214224/43536056-3dde18de-9581-11e8-9ac1-db5cf29fdcbd.png">

iOS file 

<img width="733" alt="screen shot 2018-08-01 at 11 49 54 am" src="https://user-images.githubusercontent.com/16214224/43536099-5b757b08-9581-11e8-85a7-788f1c77b76e.png">

Android file

<img width="510" alt="screen shot 2018-08-01 at 11 50 43 am" src="https://user-images.githubusercontent.com/16214224/43536113-63618f50-9581-11e8-9cec-8c738e223218.png">

**Comment by JoeMayo** [comment]
Closing - looks like a v4.x error and we're on v5.x now.
