### ISSUE TITLE
Uploading profile banner fails with missing parameter

### ISSUE THREAD

**Issue by mattbeatty** [JoeMayo/LinqToTwitter#139]
**Issue**

`UpdateProfileBannerAsync` always returns a 400 error. The response includes Twitter's error code 38 and the message "banner parameter is missing".

**Context**

I notice that `banner` is commented out in the parameters.
https://github.com/JoeMayo/LinqToTwitter/blob/cc675d8875125480e15925fe95f48961439c2e7d/src/LinqToTwitter/LinqToTwitter.Shared/Account/TwitterContextAccountCommands.cs#L417

`UpdateProfileBannerAsync` calls out to `PostMediaAsync` to attempt upload, which requires image bytes and other data specific to posting media, but this fails to add and properly encode the required banner parameters. 

See docs
https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/post-account-update_profile_banner.html

**Comment by mattbeatty** [comment]
@JoeMayo I have a fix for this that posts using `PostFormUrlEncodedToTwitterAsync` rather than `PostMediaAsync` -- with only minimal changes to allow encoding larger parameters. I will try to get that to you next week.

**Comment by mattbeatty** [comment]
PR issued here https://github.com/JoeMayo/LinqToTwitter/pull/140

**Comment by mattbeatty** [comment]
@JoeMayo Wasn't sure if you saw the PR for this yet, just checking in.

**Comment by JoeMayo** [comment]
Merged and docs updated - thanks.
