### ISSUE TITLE
"This Page Requires Info That Was Not Provided" response while PinAuthorizing

### ISSUE THREAD

**Issue by HassanElZarkawy** [JoeMayo/LinqToTwitter#14]
Hello Joe,

I'm using LinqToTwitter library for windows phone, and while using PinAuthorizer the phone browser flashes the pin and redirect to page that shows the following error "this page requres some information that was not provided". I've also tried your demos projects and i'm also getting the same response.

**Comment by JoeMayo** [comment]
Hi,

I'm aware of this issue, but haven't figured out a work-around yet. Here's my post on the Twitter dev forums:

https://twittercommunity.com/t/pin-auth-page-requires-info-not-provided/36962

Joe

**Comment by HassanElZarkawy** [comment]
Hi Joe,

I've noticed that WindowsStoreAuthorizer is not included to Windows Phone RT package by default,
and windows phone 8.1 cannot use WebAuthenticationBroker like Windows 8.1 Store apps,
so i took a copy of the class from the source code, and made it compatible with Windows Phone 8.1 RT.

I would be very happy if you gave me a contact mail to send you the sample project to be add this functionality in the next release.

**Comment by JoeMayo** [comment]
Can you DM me on Twitter?

**Comment by HassanElZarkawy** [comment]
Sure

-----Original Message-----

**Comment by JoeMayo** [comment]
LINQ to Twitter now supports UWP, where the UniversalAuthorizer is based on WebAuthenticationBroker and supports all Windows 10 devices.
