### ISSUE TITLE
Profile background images have been deprecated

### ISSUE THREAD

**Issue by mattbeatty** [JoeMayo/LinqToTwitter#141]
**Issue**

The Twitter API endpoint `post-account-update_profile_background_image` is [deprecated](https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/post-account-update_profile_background_image.html). Calling it returns a 404 with Twitter response code 34 and the message "Sorry, that page does not exist."

**Context**

Profile background images were originally deprecated by Twitter in July 2015. All support was formally [removed in May 2018](https://twittercommunity.com/t/upcoming-changes-to-the-developer-platform/104603), including Twitter removing any remaining stored data.

**Ideas**

Remove support for `UpdateAccountBackgroundImageAsync`, as it is no longer functional.

**Comment by mattbeatty** [comment]
@JoeMayo I would be happy to help with this as well.

**Comment by JoeMayo** [comment]
This is done and pushed - documentation updated.
