### ISSUE TITLE
TwitterContext ReportSpamAsync

### ISSUE THREAD

**Issue by gkirthiv** [JoeMayo/LinqToTwitter#149]
Hi All,

First of all, I did not mean this is an issue. Just asking about the ReportSpamAsync option.

Recently I downloaded LinqToTwitter from Nuget. As per the Document, there is the option with ReportSpam but not in the code. I have only ReportSpamAsync. I am sure the Blocking option is working but I wonder to know about the Report Spam. Here is my sample code

`TwitterContext ctx = new TwitterContext(....);`
`ctx.ReportSpamAsync(.....);`

Kindly let me know that I am using this ReportSpamAsync option properly or doing some mistakes?
Guidelines required.

Thank you.
Ganesh

**Comment by gkirthiv** [comment]
Cheers @JoeMayo,

Thank you very much for the reply.

I've read all the documents and tested. It reports the user as spam as expected. Code and documents are well explained and clear.

My doubt is, in the actual twitter api, they have a boolean option called "perform_block" in their api. We can block the user by single api call "report_spam".

Do LinqToTwitter have the same option? Can we block the user by using the same "Report Spam"  notification or have to call separately?

Thank you

**Comment by JoeMayo** [comment]
Documented here:

[Reporting Spam](https://github.com/JoeMayo/LinqToTwitter/wiki/Reporting-Spam)
