### ISSUE TITLE
Link image previews

### ISSUE THREAD

**Issue by nawidy** [JoeMayo/LinqToTwitter#151]
@JoeMayo thanks for your hard work on this, is the ability to get an associated mediaURL for link previews not currently supported? I had posted on the closed ticket 131 on this but haven't heard back so creating new issue to track this. 

I am unable to extract the contents of this: https://twitter.com/NawidNawidy/status/1061427542165381120

This is my query:
```
queriedTweets = await 
                    (
                        from tweet in TwitterContext.Status
                        where tweet.Type == StatusType.Lookup &&
                              tweet.TweetIDs == queryString &&
                              tweet.TweetMode == TweetMode.Extended &&
                              tweet.IncludeEntities == true
                        select tweet
                    ).ToListAsync();
```

**Comment by JoeMayo** [comment]
I'm looking at the date of this and wondering whether I've already fixed it in v5.0.

Looking at the tweet you posted, I didn't see where it had any media in it:

https://twitter.com/NawidNawidy/status/1061427542165381120

However, if you navigat to that URL, there was another tweet, under More Tweets:

https://twitter.com/ogdolo_com/status/1244321316401897474

This tweet does have media, an image, which you can find under ExtendedEntities.
