### ISSUE TITLE
Error while updating to 5.0.0 for Xamarin.Forms app

### ISSUE THREAD

**Issue by pfedotovsky** [JoeMayo/LinqToTwitter#152]
I used version 5.0.0-beta1 for Xamarin.Forms app, it works fine. Now I've updated to 5.0.0 and get the following error:

`Can not resolve reference: `System.Reactive`, referenced by `LinqToTwitter.netstandard`. Please add a NuGet package or assembly reference for `System.Reactive`, or remove the reference to `LinqToTwitter.netstandard`.	`

It's for Android project. How to fix this?

See https://github.com/pfedotovsky/XamarinForms-tests for reference

**Comment by nawidy** [comment]
I've got the same issue running from beta 3. @pfedotovsky are you building an iOS app as well?

**Comment by pfedotovsky** [comment]
@nawidy yes, iOS app is also built. But the issue is for Android project

**Comment by eliecermt** [comment]
It's been a while but if someone is having this issue i fixed it by adding manually at the Nuget Package following nugets (Shared and Android projects) System.Reactive, System.Reactive.Core, System.Reactive.Interfaces and System.Reactive.Linq.

After adding those nuggets, then clean solution, and Build.

Best regards.
