### ISSUE TITLE
Configuration Issue with asp.net core while using full.net runtime

### ISSUE THREAD

**Issue by dev-ayaz** [JoeMayo/LinqToTwitter#156]
We have an asp.net core 2.1 project but we are using .net472 as run time which works fine.
But when we try to install linqtotwitter it alwasy install  for asp.net mvc and not for asp.net core.

How can we install the linq2twitter for asp.net core while our project using .net full as run time.

**Comment by JoeMayo** [comment]
One way would be to manually install DLLs, which you can find on the Releases page for this repository.
