### ISSUE TITLE
How to implement this API in MVC

### ISSUE THREAD

**Issue by daz1761** [JoeMayo/LinqToTwitter#157]
I started to write some code in my surface controller synchronously, which worked fine, but when I read the FAQs and some general Googling, it became apparent that I had to use this API asynchronously, since I would run into problems such as deadlock, race conditions, etc.  So I changed my code to reflect this in the controller (e.g. `Task<ActionResult>` etc., but my child action method in my view was complaining of this change.  After some googling, it was clear that child action methods do no support async, so at the moment I am stuck in terms of what to do....

At the moment I use the status to pull in the latest 3 tweets.  I would like to have the media too (just the first image from each tweet.  My goal is to have an IEnumerable<model> in my partial view that contains the tweet, and image (first), for each of the 3 tweets.  Obviously, this needs to be async.

Here is my code so far:

```
public ActionResult GetTweets()
       {
           var auth = new SingleUserAuthorizer
           {
               CredentialStore = new SingleUserInMemoryCredentialStore
               {
                   // credentials
               }
           };

           var twitterCtx = new TwitterContext(auth);

           var tweets =
               (from tweet in twitterCtx.Status
                where
                tweet.Type == StatusType.User
                select tweet).Take(3).ToList();

           var model = new TwitterModel()
          // text and media will eventual populate this model

           return PartialView("~/Views/Partials/_Tweets.cshtml", model);
       }
```

**Comment by JoeMayo** [comment]
Closing - Answered in the FAQ:

https://github.com/JoeMayo/LinqToTwitter/wiki/LINQ-to-Twitter-FAQ#6-im-not-using-asyncawait-and-my-linq-to-twitter-code-isnt-working
