### ISSUE TITLE
Reverse auth credentials error

### ISSUE THREAD

**Issue by OmPJ** [JoeMayo/LinqToTwitter#158]
Hi ,
Getting the following error in await auth.CompleteAuthorizeAsync(request.Url);

**Error
Reverse auth credentials are invalid - Please visit the LINQ to Twitter FAQ (at the HelpLink) for help on resolving this error.**

Issue happens some times and not always and this started few weeks back. 
Could you please check and provide your thoughts? I see some posts on the same error in other forums also but has no solution.

Thanks

**Comment by JoeMayo** [comment]
Hi, I haven't seen this (yet?) - if it reproduces reliably, please let me know.

**Comment by OmPJ** [comment]
Thanks JoeMayo for the acknowledgement.
The failure rate is significant.
Please provide your thoughts.

**Comment by JoeMayo** [comment]
My thoughts are that as a developer I know what you're going through, the struggle of trying to figure out a difficult situation, looking for any clue to help solve it. This can be frustrating and definitely not easy.

That said, you probably know how hard it is to try to solve a problem that isn't reproducible. LINQ to Twitter has a FAQ, but this problem isn't specifically addressed there. One of the things you can try is to go through the 401 Unauthorized part of the FAQ as that's the most comprehensive information available on how to solve authorization problems. I don't know if there's a solution there for you, but it's worth a try. I've done an Internet search, which you probably have done too, and it indicates that this type of error has occurred at various times over the years on multiple technologies. Given that my applications aren't experiencing this problem and we haven't heard from other people, I don't have enough information to reproduce the problem. If I did, I would be happy to fix it. If you do find a solution please share here so others will know too.

**Comment by OmPJ** [comment]
Thanks JoeMayo.
From this error reported, Twitter support team suggested for usage of Post instead of Get HttpRequest in invoking CompleteAuthorizeAsync of LinqToTwitter. 
Post also gives same error.

On a high level, FAQ 401 unauthorized suggestions did not correlate to this. I will try to investigate more with the suggestions there.

By any chance, will the error be more specific if we try to debug by stepping in to this library code? I have not yet tried that.
Also let me know what details can be provided more to you to help me on this issue.

**Comment by JoeMayo** [comment]
Closing - I wasn't able to reproduce.
