### ISSUE TITLE
UploadMediaAsync additionalOwners parameter not having any effect. 

### ISSUE THREAD

**Issue by frapps** [JoeMayo/LinqToTwitter#159]
Hi, 

I'm trying to use the additionalOwners parameter, the method completes successfully, but when I subsequently go and post, I get an exception stating that the user doesn't have access to the media item. "User id 239986671 doesn't own media id 1110567454386896898"

Is this parameter actually being used in the underlying request to twitter? When using fiddler I can not see this has been added?

I'm using version 5. 

Thank you.

**Comment by frapps** [comment]
I believe the parameters method is not being passed to PostMediaAsync instead an empty dictionary is? 
![image](https://user-images.githubusercontent.com/15358499/55014712-5db7ae00-4fe3-11e9-8998-49890f3bdeac.png)

**Comment by JoeMayo** [comment]
Thanks for pointing out the fix - this is done and merged.
