### ISSUE TITLE
UploadMediaAsync 

### ISSUE THREAD

**Issue by Git-Twitter** [JoeMayo/LinqToTwitter#160]
unable to post tweet of mp4 file using linqtotwitter library

**Comment by mikemike396** [comment]
Same here any update?

**Comment by JoeMayo** [comment]
Video uploads are working for me. I've updated the ConsoleSamples code that includes two separate videos: `TwitterTest.mp4` and `LinqToTwitterErrorText.mp4`. This lets you use the demo code to test both a video that works and one that doesn't work, respectively, and write error handling code. The difference between the two is that `LinqToTwitterErrorText.mp4` is intentionally larger than what Twitter allows.

Please review the Twitter API [Media Best Practices](https://developer.twitter.com/en/docs/media/upload-media/uploading-media/media-best-practices) for more information on what video attributes and formats are allowed.
