### ISSUE TITLE
Can't find the 5.0.0 release

### ISSUE THREAD

**Issue by rtaborda** [JoeMayo/LinqToTwitter#161]
Hi,

The latest release I can find here in github is v4.2.1, but in the nuget repository there's already version v5.0.0. Any reason why that is currently not available/visible here?

![image](https://user-images.githubusercontent.com/12414897/56903893-78c38500-6a9d-11e9-8a01-4e8510d5ad00.png)

![image](https://user-images.githubusercontent.com/12414897/56903938-8a0c9180-6a9d-11e9-86da-14d6a75e8a49.png)

**Comment by mikemike396** [comment]
Any update @JoeMayo

**Comment by cecilphillip** [comment]
He probably just forgot to tag it

**Comment by JoeMayo** [comment]
I'm running behind the curve on this one - it's released now:

[LINQ to Twitter v5.0.0 Release](https://github.com/JoeMayo/LinqToTwitter/releases/tag/v5.0.0)
