### ISSUE TITLE
Add Query parameters to callback URL in BeginAuthorizationAsync

### ISSUE THREAD

**Issue by rahuljoshi05** [JoeMayo/LinqToTwitter#163]
https://developer.twitter.com/en/docs/basics/apps/guides/callback-urls.html

Twitter developer guide mentions we can add additional parameters, is there a way I can add additional parameters? BeginAuthorizationAsync is an action result that redirects. How can I pass my parameter to Twitter so I get it back

**Comment by rahuljoshi05** [comment]
I just saw the Twitter doc mention request_token step, but I want to add a parameter in the first step in the oauth/authenticate URL so when twitter redirects back I can fetch some details on the session. I dont want to rely on the MVC session. Is it possible to add additional parameters that I can later use to identify some details about the origination of the session.

**Comment by JoeMayo** [comment]
Just checked this in. It works like this:

```cs
var parameters = new Dictionary<string, string> { { "my_custom_param", "val" } };
string twitterCallbackUrl = Request.GetDisplayUrl().Replace("Begin", "Complete");
return await auth.BeginAuthorizationAsync(new Uri(twitterCallbackUrl), parameters);
```

And then you can read the parameters via `Request.QueryString` in the `Complete()` action.
