### ISSUE TITLE
Does LinQ to Twitter use TLS 1.2 as Twitter will require it beginning July 15th 2019?

### ISSUE THREAD

**Issue by gitbrook** [JoeMayo/LinqToTwitter#164]
Hi, we ran some tests to capture the server traffic with the tool wireshark, and when we tweet from our Win 2008 server with an app running LinQToTwitter V 2.1.8.0 it says the protocol in use is TLSv1 . 

We also have an application running LinQToTwitter V 5 on a Win 2016 server and wireshark states it is using TLSv1 as well.

Both servers show traffic from different applications sending out TLSv1.2 traffic, so we know the servers can handle TLSV1.2 traffic. 

How can we get the apps using LinQToTwitter to send out using TLSv1.2? It is important as on July 15 the Twitter API will require TLS 1.2. 

More details from Twitter: 
https://twittercommunity.com/t/removing-support-for-legacy-tls-versions-1-0-1-1-on-twitter/126648/2

**Comment by gitbrook** [comment]
Found out this was actually a .Net issue, and was able to resolve it by specifying the TLS version per: https://blogs.perficient.com/2016/04/28/tsl-1-2-and-net-support/

**Comment by gitbrook** [comment]
Found out this was actually a .Net issue, and was able to resolve it by specifying the TLS version per: https://blogs.perficient.com/2016/04/28/tsl-1-2-and-net-support/

**Comment by rangler2** [comment]
Does this mean, that the library does not specify TLS 1.2 and you have to ensure that .NET is configured to do so to avoid errors? As shown in #114 :

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

.NET Framework 4.6.2 has TLS 1.2 enabled out of the box but earlier versions might need to have code like the above to enable 1.2 , unless the library does this internally. Which I assume it does not?

**Comment by mikemike396** [comment]
> Found out this was actually a .Net issue, and was able to resolve it by specifying the TLS version per: https://blogs.perficient.com/2016/04/28/tsl-1-2-and-net-support/

Did you just put this line before calling "TweetAsync" ? 

    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

**Comment by kharaone** [comment]
That's what I did in my project and solved the issue. 
However, you might need to surround the code instead as close as possible as you need it.
`var originalSecurityProtocol = ServicePointManager.SecurityProtocol;`
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`
`var status = await twitterContext.TweetAsync(post.News);`
`ServicePointManager.SecurityProtocol = originalSecurityProtocol;`

**Comment by ronaldbarendse** [comment]
The blogpost @gitbrook linked is incorrect about _The following code will make TLS 1.2 default_, as `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12` will **only** allow TLS 1.2 connections, so can't connect to servers only supporting older protocols!

The following code can be added to the `Application_Start` or some other place that only executes once and will only change the protocols if it's not set to the system default (https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.securityprotocol):
```c#
if (ServicePointManager.SecurityProtocol != 0)
{
	// Remove SSL3 and TLS 1.0, add TLS 1.1 and TLS 1.2
	ServicePointManager.SecurityProtocol &= ~SecurityProtocolType.Ssl3;
	ServicePointManager.SecurityProtocol &= ~SecurityProtocolType.Tls;
	ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11;
	ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
}
```
