### ISSUE TITLE
Error when use SinceID param

### ISSUE THREAD

**Issue by TirianM** [JoeMayo/LinqToTwitter#166]
Hi, 
The parameter SinceID isn't work properly. 
Im using v 5.0.

When i set the value with1 , the response is correct.

![image](https://user-images.githubusercontent.com/54116393/63041944-90791a80-be8e-11e9-8bd4-5c73031e3a22.png)

But if i set other value the response get an exception.

![image](https://user-images.githubusercontent.com/54116393/63042092-ea79e000-be8e-11e9-92e0-2a14f70f62a2.png)

![image](https://user-images.githubusercontent.com/54116393/63042180-14330700-be8f-11e9-8f56-a48105e9c987.png)

This is the tweet in the example.

![image](https://user-images.githubusercontent.com/54116393/63042399-899ed780-be8f-11e9-885f-cbf8f37618ea.png)

StackTrace
   en LinqToTwitter.Net.TwitterErrorHandler.BuildAndThrowTwitterQueryException(String responseStr, HttpResponseMessage msg)
   en LinqToTwitter.Net.TwitterErrorHandler.<HandleGenericErrorAsync>d__1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en LinqToTwitter.Net.TwitterErrorHandler.<ThrowIfErrorAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en LinqToTwitter.TwitterExecute.<HandleResponseAsync>d__61.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en LinqToTwitter.TwitterExecute.<QueryTwitterAsync>d__48`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en LinqToTwitter.TwitterContext.<ExecuteAsync>d__136`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en LinqToTwitter.TwitterQueryProvider.<ExecuteAsync>d__8`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en LinqToTwitter.TwitterExtensions.<SingleOrDefaultAsync>d__5`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by JoeMayo** [comment]
Closing - Old and TBE - BTW, we can't set SinceID to 0 because the first tweet ID is 1 and that's what you should start with when paging the first time.
