### ISSUE TITLE
problem trying to mocking TwitterContext

### ISSUE THREAD

**Issue by lucamorelli** [JoeMayo/LinqToTwitter#17]
Hi, I don't know if this is the right place to ask this, but I have a problem writing a few tests for an application using linq2 twitter.    
I copied this code from the test from create the Mock of a TwitterContext

		private Mock<TwitterContext> ctx;
		private Mock<ITwitterExecute> execMock;
		private Mock<IRequestProcessor<Status>> statusReqProc;

		readonly byte[] imageBytes = new byte[] { 0xFF };

		string status = "test";
		bool possiblySensitive = true;
		decimal latitude = 37.78215m;
		ulong inReplyToStatusID = 23030327348932ul;

		[TestMethod]
		public async Task IfRaiseExceptionSendingIsSkippedAndProcessingContinue()
		{
			statusReqProc = new Mock<IRequestProcessor<Status>>();
			statusReqProc.Setup(reqProc => reqProc.ProcessResults(It.IsAny<string>()))
			.Returns(new List<Status> { new Status { Text = "Test" } });

			execMock = new Mock<ITwitterExecute>();
			var authMock = new Mock<IAuthorizer>();
			var tcsResponse = new TaskCompletionSource<string>();
			tcsResponse.SetResult(SingleStatusResponse);
			execMock = new Mock<ITwitterExecute>();
			execMock.SetupGet(exec => exec.Authorizer).Returns(authMock.Object);
			execMock.Setup(
				exec => exec.PostMediaAsync(
					It.IsAny<string>(),
					It.IsAny<Dictionary<string, string>>(),
					It.IsAny<byte[]>(),
					It.IsAny<string>(),
					It.IsAny<string>(),
					It.IsAny<string>(),
					It.IsAny<CancellationToken>()))
					.Returns(tcsResponse.Task);

			ctx = new Mock<TwitterContext>(execMock.Object);

I would like to add something similar

			ctx.Setup(mock => mock.TweetAsync("wrong"))
				.ThrowsAsync(new InvalidOperationException());

so when in the execution of the test try to send a specific tweet in a block of others in raised an exception, but when this setup is called I receive an error message.  
Am I missing something?

**Comment by JoeMayo** [comment]
Hi,
I received the following exception:
```
Test Name:	TweetAsync_Throws_On_Bad_Tweet
Test FullName:	LinqToTwitterPcl.Tests.StatusTests.StatusCommandsTests.TweetAsync_Throws_On_Bad_Tweet
Test Source:	C:\Projects\LinqToTwitter\New\Tests\LinqToTwitterPcl.Tests\StatusTests\StatusCommandsTests.cs : line 103
Test Outcome:	Failed
Test Duration:	0:00:00.8217211

Result StackTrace:	
at Moq.Mock.ThrowIfCantOverride(Expression setup, MethodInfo method)
   at Moq.Mock.<>c__DisplayClass1c`2.<Setup>b__1b()
   at Moq.PexProtector.Invoke[T](Func`1 function)
   at Moq.Mock.Setup[T,TResult](Mock`1 mock, Expression`1 expression, Condition condition)
   at Moq.Mock`1.Setup[TResult](Expression`1 expression)
   at LinqToTwitterPcl.Tests.StatusTests.StatusCommandsTests.<TweetAsync_Throws_On_Bad_Tweet>d__6.MoveNext() in C:\Projects\LinqToTwitter\New\Tests\LinqToTwitterPcl.Tests\StatusTests\StatusCommandsTests.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Result Message:	
Test method LinqToTwitterPcl.Tests.StatusTests.StatusCommandsTests.TweetAsync_Throws_On_Bad_Tweet threw exception: 
System.NotSupportedException: Invalid setup on a non-virtual (overridable in VB) member: mock => mock.TweetAsync(null)
```
Is that the same error you encountered? If so, it's because Moq requires it to be virtual and it isn't. If I make the method virtual, like the following, it works:
```C#
        public virtual async Task<Status> TweetAsync(string status)
```
I created a helper method for this scenario, see the TweetAsync_Throws_On_Null_Tweet test, which has this:
```C#
        public async Task TweetAsync_Throws_On_Null_Tweet()
        {
            var ctx = await InitializeTwitterContext();

            var ex = await L2TAssert.Throws<ArgumentException>(
                async () => await ctx.TweetAsync(null));

            Assert.AreEqual("status", ex.ParamName);
        }
```
What are you thinking about the pros and cons of making all side-effects virtual vs. the helper method?

**Comment by JoeMayo** [comment]
No response - issue closed.
