### ISSUE TITLE
Can't set tweetmode to extended when querying list

### ISSUE THREAD

**Issue by AsianPotato** [JoeMayo/LinqToTwitter#171]
When querying statuses from a list it is not possible to set the tweetmode to extended. Is it possible to make a twittercontext always have tweetmode as extended? Or is there any other way to set tweetmode to extended?

**Comment by AsianPotato** [comment]
User lookup should also have tweetmode but doesn't

**Comment by Badabum** [comment]
@AsianPotato I think it's a good feature to create a PR for :)

**Comment by JoeMayo** [comment]
This is updated with `TweetMode `support for `TweetAsync`, `ReplyAsync`, and `User `queries. `Status `query support was already there. Here are a few examples:

Tweets:

	Status tweet = await twitterCtx.TweetAsync(status, tweetMode: TweetMode.Extended);

Status Queries:

	List<Status> status =
		await
		(from tweet in twitterCtx.Status
		 where tweet.Type == StatusType.Show &&
			   tweet.ID == tweetID &&
			   tweet.TweetMode == TweetMode.Extended &&
			   tweet.IncludeAltText == true
		 select tweet)
		.ToListAsync();
		
User Queries:

	var userResponse =
		await
		(from user in twitterCtx.User
		 where user.Type == UserType.Lookup &&
			   user.ScreenNameList == "JoeMayo,Linq2Twitr" &&
			   user.TweetMode == TweetMode.Extended
		 select user)
		.ToListAsync();

Your suggestion for making `TweetMode.Extended` be the default makes sense at first glance. However, after several years and over a million downloads, there are many people using the library and this would be a breaking change. Sometimes, I can make a breaking change that no one notices and other times the break will meet with a lot of dissatisfaction. I believe this falls into the later case and would not be helpful to the majority of developers. Additionally, the Twitter default is still `compat` and they haven't changed and it's often disruptive for my implementation to stray too far from the default behavior of the Twitter API. They're building a new API and we won't need a mode as the only mode will be extended.
