### ISSUE TITLE
Developer Labs / next Twitter API

### ISSUE THREAD

**Issue by andypiper** [JoeMayo/LinqToTwitter#172]
Hello from Twitter Developer Relations!

First of all: Thank You, Joe, for building on our API, and for supporting our developer communities! You, and many projects like this one, are among the reasons why Twitter data is much-appreciated by developers. We historically haven't built libraries and SDKs - the communities, YOU, have done so - and I'm here to tell you how much we appreciate that, and that we know you're around!

We're currently building a brand new API platform that (over time) will replace the current one. I would love to connect with you on any plans to add support for Twitter Developer Labs! We're looking to be much more focused on proper API versioning, and are basing our specification on OpenAPI.

As we hope you know, we do list LinqToTwitter on our developer libraries page https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries and we would really love to continue to do so as you continue to help the .NET community. Thank you, again!

**Comment by JoeMayo** [comment]
Hi Andy,

Thanks for sharing Twitter's appreciation for community libraries. I still believe the Twitter API has a lot of potential and look forward to continuing my support and building on the platform. You're welcome to contact me any time.

Regards,

Joe
[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by andypiper** [comment]
Thanks, will follow up soon.
