### ISSUE TITLE
User object missing an "Entities" property

### ISSUE THREAD

**Issue by joshua-montgomery-fox** [JoeMayo/LinqToTwitter#173]
Hi, 

We are using the User Search functionality and have noticed that an "Entities" property on the "User" object is missing. An example of this data in the Twitter API : https://api.twitter.com/1.1/users/search.json?q=devin booker

![image](https://user-images.githubusercontent.com/56365262/77855768-a4c11c00-71c0-11ea-9184-9a84c14e94ab.png)

**Comment by JoeMayo** [comment]
I must have missed that - thanks for letting me know.

**Comment by JoeMayo** [comment]
Fixed, pushed, and documented.
