### ISSUE TITLE
No support for expanded and enhanced urls

### ISSUE THREAD

**Issue by Ri3gs** [JoeMayo/LinqToTwitter#175]
Twitter is offering this: 
https://developer.twitter.com/en/docs/tweets/enrichments/overview/expanded-and-enhanced-urls which enhances external urls in entities object with a title and a description. 

Currently, there's no support for this in LinqToTwitter UrlEntity class.

**Comment by JoeMayo** [comment]
Thanks for the heads up. A current work-around is to read the JSON from the `twitterCtx.RawResults` property.

**Comment by JoeMayo** [comment]
Just doing research on this and I don't believe I have access to this API. If this was the free API, I would be able to test it. I don't have an enterprise subscription. If you or someone else wants to add this, I can accept a pull request.
