### ISSUE TITLE
Search in Twitter Without Authenticated

### ISSUE THREAD

**Issue by alirezaseif28** [JoeMayo/LinqToTwitter#177]
Hi.
Best Regards.
How Search in Twitter Without Authenticated

**Comment by JoeMayo** [comment]
Hi,

The Twitter API requires authentication for all endpoints, including Search. 

That said, you don't have to go through the OAuth process. To do that, load the authorizer with all 4 credentials, from your Twitter App, and that will work. For examples, see

[Single User Authorization](https://github.com/JoeMayo/LinqToTwitter/wiki/Single-User-Authorization)

and 

[Application-Only Authorization](https://github.com/JoeMayo/LinqToTwitter/wiki/Application-Only-Authorization)

Here's the [LINQ to Twitter Security](https://github.com/JoeMayo/LinqToTwitter/wiki/Securing-Your-Applications) page.

[@JoeMayo](https://twitter.com/JoeMayo)
