### ISSUE TITLE
Duplicate JsonProperty value in UserEntities class

### ISSUE THREAD

**Issue by karlmargerum** [JoeMayo/LinqToTwitter#179]
Hi, I cannot serialise certain items I source such as the userTweets object below due to a duplicate jsonProperty value of "url" on more than one property in the UserEntities class.

`
                var tweetsUser = from tweet in _twitterContext.Status
                    where tweet.Type == StatusType.Mentions &&
                          tweet.Count == 100 &&
                          tweet.ExcludeReplies == false
                    select tweet;
                var userTweets = tweetsUser.ToList();
`

I have attached the user entities class here where value of "url" appears to be incorrectly assigned to the Description property.

`
namespace LinqToTwitter
{
    public class UserEntities
    {
        [JsonProperty("url")]
        public Entities Description
        {
            get;
            set;
        }

        [JsonProperty("url")]
        public Entities Url
        {
            get;
            set;
        }

        public UserEntities(JsonData entities)
        {
            this.Url = new Entities(entities.GetValue<JsonData>("url"));
            this.Description = new Entities(entities.GetValue<JsonData>("description"));
        }
    }
}
`

Thanks in advance

**Comment by JoeMayo** [comment]
Thanks for reporting.

**Comment by JoeMayo** [comment]
Fixed and pushed to NuGet: https://www.nuget.org/packages/linqtotwitter/5.1.2
