### ISSUE TITLE
Retweet returns 401 

### ISSUE THREAD

**Issue by apobekiaris** [JoeMayo/LinqToTwitter#182]
When I try to retweet anything I get a 401. The account also looks fine as I can retweet the same StatusID from twitter.com, the context is also ok because I verify it and also it is possible to tweet.
I also verify it against the net48 consoleapp demo and tried multiple accounts.

any pointers I possibly miss?

**Comment by JoeMayo** [comment]
That was a bug in the code. I fixed and pushed the changes. I have a couple other issues to look at and will probably deploy a new bug fix version to NuGet soon.

**Comment by JoeMayo** [comment]
Fixed and pushed to NuGet: https://www.nuget.org/packages/linqtotwitter/5.1.2
