### ISSUE TITLE
Get Full text in search hashtag

### ISSUE THREAD

**Issue by alirezaseif28** [JoeMayo/LinqToTwitter#189]
Hi
I have a function below.for search in twitter.

`

        static async Task DoPagedSearchAsync(TwitterContext twitterCtx)
           {
               const int MaxSearchEntriesToReturn = 20;

            string searchTerm = "term";

            // oldest id you already have for this search term
            ulong sinceID = 1;

            // used after the first query to track current session
            ulong maxID;

            var combinedSearchResults = new List<Status>();

            List<Status> searchResponse =
                await
                (from search in twitterCtx.Search
                 where search.Type == SearchType.Search &&
                       search.Query == searchTerm &&
                       search.Count == MaxSearchEntriesToReturn &&
                       search.SinceID == sinceID
                 select search.Statuses)
                .SingleOrDefaultAsync();

            combinedSearchResults.AddRange(searchResponse);
            ulong previousMaxID = ulong.MaxValue;
            do
            {
                // one less than the newest id you've just queried
                maxID = searchResponse.Min(status => status.StatusID) - 1;

                Debug.Assert(maxID < previousMaxID);
                previousMaxID = maxID;

                searchResponse =
                    await
                    (from search in twitterCtx.Search
                     where search.Type == SearchType.Search &&
                           search.Query == searchTerm &&
                           search.Count == MaxSearchEntriesToReturn &&
                           search.MaxID == maxID &&
                           search.SinceID == sinceID
                     select search.Statuses)
                    .SingleOrDefaultAsync();

                combinedSearchResults.AddRange(searchResponse);
            } while (searchResponse.Any());

            
            var result = combinedSearchResults.Select(x => new {
                ScreenNameResponse=  x.User.ScreenNameResponse,
                UserIDResponse= x.User.UserIDResponse,
                Text=x.Text,
                Likes = x.FavoriteCount,
                follower = x.User.FollowersCount,
                fallowing = x.User.FriendsCount,
                RetwitCount = x.RetweetCount
            }).ToList();
           
        }
`
this is a tweet text with count flower and following and retweet.
how get full text ?

best regard

**Comment by JoeMayo** [comment]
Hi,

You can set `TweetMode `to `Extended`. Back when Twitter went from 140 characters to 280, they introduced this as a way to get the full 280 characters. So, instead of looking in the `Text` property, you can look at the `FullText` property. Here's how to change your query:

    List<Status> searchResponse =
        await
        (from search in twitterCtx.Search
            where search.Type == SearchType.Search &&
                search.Query == searchTerm &&
                search.Count == MaxSearchEntriesToReturn &&
                search.SinceID == sinceID &&
                search.TweetMode == TweetMode.Extended
            select search.Statuses)
        .SingleOrDefaultAsync();

Notice that I added `search.TweetMode == TweetMode.Extended`.

**Comment by alirezaseif28** [comment]
Hi .thank you for replies.
My problem now is this. I'm searching for a word and the results are about 3. But on Twitter, when I search for that word, the results are much higher.
How do I fix this?

best regard

**Comment by JoeMayo** [comment]
As described here in the Twitter API documentation on [Search Tweets](https://developer.twitter.com/en/docs/tweets/search/overview), there are different levels of search, Standard, Premium, and Enterprise. The Standard level is free and only goes back 7 days. If your 3 are within that 7 days and the rest are later, it would indicate that their search is using one of the premium APIs. 

On the [Standard Search API](https://developer.twitter.com/en/docs/tweets/search/overview/standard) documentation they state:

> The Twitter's standard search API (search/tweets) allows simple queries against the indices of recent or popular Tweets and behaves similarly to, but not exactly like the Search UI feature available in Twitter mobile or web clients.

They don't define what `but not exactly like` means. You might want to look at the documentation and compare that to the behavior you're seeing to see if you can tweak search parameters to something closer to what their results are.

**Comment by alirezaseif28** [comment]
thank you.
How to get all the data in history
please guide me

**Comment by JoeMayo** [comment]
[Twitter's Premium Search](https://developer.twitter.com/en/docs/tweets/search/guides/integrating-premium) gives you full archive access. I'm currently only supporting the free API. If you  decide to use premium and find that the normal LINQ to Twitter Search query doesn't support all parameters, you can use [Raw Queries](https://github.com/JoeMayo/LinqToTwitter/wiki/Raw-Queries).
