### ISSUE TITLE
Quoted Tweets

### ISSUE THREAD

**Issue by JoeMayo** [JoeMayo/LinqToTwitter#19]
Twitter is adding new fields to support quoted tweets, which need to be added to L2T:

https://twittercommunity.com/t/api-payloads-to-include-original-quoted-tweet-objects/38184

**Comment by Dashue** [comment]
I'll be using this as soon as it's off the press! :) Thanks for your good work!

**Comment by Dashue** [comment]
Got any estimate to when this will arrive?

Thanks

**Comment by JoeMayo** [comment]
Completed via @nitroin pull request.
