### ISSUE TITLE
linq-to-twitter Twitter flood get

### ISSUE THREAD

**Issue by omerxkorkmaz** [JoeMayo/LinqToTwitter#193]
Hi everyone,

I tried the code below but again it wasn't exactly as I wanted. Only 1 pearl flood is coming.

There are 90 floods. RT ones should not come and should only come flood by call.

as an example I shared the picture. What do I have to do in this situation.

I did but I have Count=0. Why ?

There is registration on this site. How this site does it. Do you know below website.

how do i add the following code in_reply_to_status_id. I think it can be solved this way.

https://threadreaderapp.com/search?q=HANEDANLAR+MASASININ+YER+ALTI+EGEMENL%C4%B0%C4%9E%C4%B0%3AR%C4%B0O+T%C4%B0NTO

`const int MaxSearchEntriesToReturn = 100;
        const int SearchRateLimit = 180;

       var myFilter = "-filter:retweets";
        string searchTerm = "HANEDANLAR MASASININ YER ALTI EGEMENLİĞİ:RİO TİNTO " + myFilter;

        // oldest id you already have for this search term
        ulong sinceID = 1;

        // used after the first query to track current session
        ulong maxID;

        var combinedSearchResults = new List<Status>();

        List<Status> searchResponse =
            await
            (from search in ctx.Search
             where search.Type == SearchType.Search &&
                   search.Query == searchTerm &&
                   search.Count == MaxSearchEntriesToReturn &&
                   search.SinceID == sinceID &&
                   search.TweetMode == TweetMode.Extended
             select search.Statuses)
            .SingleOrDefaultAsync();

        if (searchResponse != null)
        {
            combinedSearchResults.AddRange(searchResponse);
            ulong previousMaxID = ulong.MaxValue;
            do
            {
                // one less than the newest id you've just queried
                maxID = searchResponse.Min(status => status.StatusID) - 1;

                Debug.Assert(maxID < previousMaxID);
                previousMaxID = maxID;

                searchResponse =
                    await
                    (from search in ctx.Search
                     where search.Type == SearchType.Search &&
                           search.Query == searchTerm &&
                           search.Count == MaxSearchEntriesToReturn &&
                           search.MaxID == maxID &&
                           search.SinceID == sinceID &&
                           search.TweetMode == TweetMode.Extended
                     select search.Statuses)
                    .SingleOrDefaultAsync();

                combinedSearchResults.AddRange(searchResponse);
            } while (searchResponse.Any() && combinedSearchResults.Count < SearchRateLimit);

            combinedSearchResults.ForEach(tweet => 
                Console.WriteLine(
                    "\n  User: {0} ({1})\n  Tweet: {2}",

                    tweet.User.ScreenNameResponse,
                    tweet.User.UserIDResponse,
                    tweet.Text ?? tweet.FullText)
                );
        }
        else
        {
            Console.WriteLine("No entries found.");
        }

        ViewBag.Twet = combinedSearchResults.ToList();
![flod](https://user-images.githubusercontent.com/19975134/82833087-b9bae280-9ec5-11ea-8485-34fc6f5bfde3.png)
`

**Comment by JoeMayo** [comment]
Answered on SO: https://stackoverflow.com/questions/61872234/linq-to-twitter-twitter-flood-get
