### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Petje1972** [JoeMayo/LinqToTwitter#198]
Hello,

Not an issue, Just a question,
I currently have an old project (vb.net 4.0) where Linq2Twitter 2.1.11 was used to read last tweets from a user and/or do a search. We recently noticed that the old code (dated back to 2013) is not working anymore...

Can this old version (2.1.11) still communicate with Twitter or is there so much changed at Twitters end that an upgrade has to be done?

Grtz Patrick Vossen

**Comment by JoeMayo** [comment]
Hi,

I just looked and it seems to be using Twitter API v1.1 endpoints, which are current. It might work - though some of the endpoints might be deprecated. You can find the code here:

https://github.com/JoeMayo/LinqToTwitter/tree/main/src/LinqToTwitter3

I'm not maintaining older versions, but will accept a pull request if you wanted to add/fix anything.

Joe

**Comment by Petje1972** [comment]
Hi Joe,

Thanks 4 your response.
I will check it out.

Grtz Patrick
