### ISSUE TITLE
Documentation For UploadMediaAsync / TweetASync

### ISSUE THREAD

**Issue by robdevelop** [JoeMayo/LinqToTwitter#2]
Just wondering if some documentation for the UploadMediaAsync could be posted, along with how to attach a mediaID to a tweet with TweetASync. 

Am trying to do this in VB.net and although I can get back a Media Instance am having trouble attaching a MediaID to a tweet. 

Many Thanks

**Comment by JoeMayo** [comment]
Hi,

Here's a blog post I wrote and there are demos in the code:

http://geekswithblogs.net/WinAZ/archive/2014/10/21/uploading-multiple-images-in-parallel-with-async-and-linq-to.aspx

I'll leave this issue open in case someone updates the wiki before I get to it.

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by JoeMayo** [comment]
Updated docs to include UploadMediaAsync. Also added entity definitions for Media and MediaImage: https://github.com/JoeMayo/LinqToTwitter/wiki/Uploading-And-Tweeting-Media
