### ISSUE TITLE
Deserialize Objects from Stream

### ISSUE THREAD

**Issue by nitroin** [JoeMayo/LinqToTwitter#20]
Hi Joe,

this look like much more like a question instead of an issue.

How can the objects received from the stream be deserialized to be mapped with the C# typed objects?

In an UWP project I'm trying the following:

await TwitterCtx.Streaming.Where(stream => stream.Type == StreamingType.User).StartAsync(async (payload) =>

(cut)

switch (payload.EntityType)

(cut)

DirectMessage message = new DirectMessage(payload.Content);

But I'm unable to have the object correctly populated.

Thank you.

**Comment by JoeMayo** [comment]
Hi,

_StreamContent_ has _EntityType_ and _Entity_ properties to help extract a typed object. The following demo:

https://github.com/JoeMayo/LinqToTwitter/blob/master/Samples/net46/CSharp/ConsoleSamples/StreamDemos.cs

Has a _HandleStreamResponse_ method that uses those properties.

**Comment by nitroin** [comment]
Can't belive it was so easy. Thank you.
