### ISSUE TITLE
5.1.2 is broken on framework 4.8

### ISSUE THREAD

**Issue by ispysoftware** [JoeMayo/LinqToTwitter#200]
Installing via nuget into a new (framework 4.8) web project the linqtotwitter.netstandard dll isn't included so you get:

"the type 'IAuthorizer' is defined in an assembly that is not referenced. You must add a reference to assembly 'LinqToTwitter.netstandard, Version=5.1.2.0, Culture=neutral, PublicKeyToken=null'"

**Comment by ispysoftware** [comment]
rolling back to v5.0.0 resolves it

**Comment by JoeMayo** [comment]
Hi,

I see what the problem is. Thanks for reporting.

Joe

**Comment by JoeMayo** [comment]
This fix is checked-in, pushed to NuGet, and has a new 5.1.3 release.

**Comment by SamKO91** [comment]
Joe,
I'm getting the same issue with a Asp.Net Core 3.1 app and updating to 5.1.3 didn't resolve the issue.

**Comment by JoeMayo** [comment]
SamKO91,

I tried to repro on ASP.NET Core 3.1, but couldn't. Can you uninstall the LINQ to Twitter DLLs, making sure you remove any "linqtotwitter.netstandard" dlls that might have been pulled in, and then reinstall?

Joe
