### ISSUE TITLE
vb.net: not valid video

### ISSUE THREAD

**Issue by geziri** [JoeMayo/LinqToTwitter#204]
Hi,
I try to upload video "10" second with size 3 MB 
but getting error "not valid video"
Mu code is :
 ` 
Dim auth = New SingleUserAuthorizer With {
            .CredentialStore = New SingleUserInMemoryCredentialStore With {
                 .ConsumerKey = ConsumerKey,
                  .ConsumerSecret = ConsumerSecret,
                  .AccessToken = AccessToken,
                  .AccessTokenSecret = AccessTokenSecret
            }
        }
                    Dim twitterCtx = New TwitterContext(auth)
                    Dim imageBytes As Byte() = File.ReadAllBytes(Clip_Filename)
                    Const JoeMayoUserID As ULong = 15411837
                    Dim additionalOwners = New ULong() {JoeMayoUserID}
                    Dim mediaType As String = "video/mp4"
                Dim mediaCategory As String = "tweet_video"
                Dim media = Await twitterCtx.UploadMediaAsync(imageBytes, mediaType, additionalOwners, mediaCategory)
                Dim mediaIds = New List(Of ULong) From {
                        media.MediaID
                    }
                    If RTB_CAP.Text.Length > 270 Then
                        TWEET_TXT = RTB_CAP.Text.Substring(0, 270) & "..."
                    Else
                        TWEET_TXT = RTB_CAP.Text.Trim
                    End If
                    Dim tweet As Status = Await twitterCtx.TweetAsync(TWEET_TXT.Trim, mediaIds)
                    If tweet IsNot Nothing Then MsgBox($"Tweet sent: {tweet.Text}")

`

**Comment by JoeMayo** [comment]
Hi,

Videos can take time to upload and if you tweet before it's ready, you'll get an error. This demo code uses a do/while loop to verify that the video uploaded okay:

https://github.com/JoeMayo/LinqToTwitter/blob/main/Samples/LinqToTwitter5/net48/CSharp/ConsoleSamples/MediaDemos.cs

You might also want to review the Twitter docs to verify the video requirements:

https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/overview

[@JoeMayo ](https://twitter.com/JoeMayo)

**Comment by geziri** [comment]
Thank you for reply ,
I have problem with this code not working on vb.net :
mediaStatusResponse = Await (From stat In twitterCtx.Media Where stat.Type = MediaType.Status AndAlso stat.MediaID = media.MediaID Select stat).SingleOrDefaultAsync()

Getting error

**Comment by geziri** [comment]
this code is correct :
but not uploading :
`
Dim auth = New SingleUserAuthorizer With {
                .CredentialStore = New SingleUserInMemoryCredentialStore With {
                     .ConsumerKey = ConsumerKey,
                      .ConsumerSecret = ConsumerSecret,
                      .AccessToken = AccessToken,
                      .AccessTokenSecret = AccessTokenSecret
                }
            }
                Dim twitterCtx = New TwitterContext(auth)
                Dim imageBytes As Byte() = File.ReadAllBytes(Clip_Filename)
                Const JoeMayoUserID As ULong = 15411837
                Dim additionalOwners = New ULong() {JoeMayoUserID}
                Dim status As String
                If RTB_CAP.Text.Length > 270 Then
                    status = RTB_CAP.Text.Substring(0, 270) & "..."
                Else
                    status = RTB_CAP.Text.Trim
                End If
                Dim mediaType1 As String = "video/mp4"
                Dim mediaCategory As String = "tweet_video"
                Dim media As Media = Await twitterCtx.UploadMediaAsync(imageBytes, mediaType1, additionalOwners, mediaCategory)
                Dim mediaStatusResponse As Media = Nothing

                Do

                    If mediaStatusResponse IsNot Nothing Then
                        Dim checkAfterSeconds As Integer = If(mediaStatusResponse?.ProcessingInfo?.CheckAfterSeconds, 0)
                        Console.WriteLine($"Twitter video testing in progress - waiting {checkAfterSeconds} seconds.")
                        Await Task.Delay(checkAfterSeconds * 1000)
                    End If
                    mediaStatusResponse = Await (From stat In twitterCtx.Media Where stat.Type = MediaType.Status AndAlso stat.MediaID = media.MediaID Select stat).SingleOrDefaultAsync()


                Loop While mediaStatusResponse?.ProcessingInfo?.State Is MediaProcessingInfo.InProgress

                If mediaStatusResponse?.ProcessingInfo?.State Is MediaProcessingInfo.Succeeded Then
                    Dim tweet22 As Status = Await twitterCtx.TweetAsync(status.Trim, New ULong() {media.MediaID})
                    If tweet22 IsNot Nothing Then Console.WriteLine($"Tweet sent: {tweet22.Text}")
                Else
                    Dim [error] As MediaError = mediaStatusResponse?.ProcessingInfo?.[Error]
                    If [error] IsNot Nothing Then Console.WriteLine($"Request failed - Code: {[error].Code}, Name: {[error].Name}, Message: {[error].Message}")
                End If


            Catch ex As Exception
                MsgBox(ex.Message)
            End Try
`

**Comment by JoeMayo** [comment]
I got this to work:

    Public Async Function UploadMedia(twitterCtx As TwitterContext) As Task
        Dim Clip_Filename As String = "..\..\..\Images\TwitterTest.mp4"
        Dim imageBytes As Byte() = File.ReadAllBytes(Clip_Filename)
        Const JoeMayoUserID As ULong = 15411837
        Dim additionalOwners = New ULong() {JoeMayoUserID}
        Dim status As String = "Testing video upload tweet #Linq2Twitter £ " +
                DateTime.Now.ToString(CultureInfo.InvariantCulture)
        Dim mediaType1 As String = "video/mp4"
        Dim mediaCategory As String = "tweet_video"
        Dim media As Media = Await twitterCtx.UploadMediaAsync(imageBytes, mediaType1, additionalOwners, mediaCategory)
        Dim mediaStatusResponse As Media = Nothing
        Do

            If mediaStatusResponse IsNot Nothing Then
                Dim checkAfterSeconds As Integer = If(mediaStatusResponse?.ProcessingInfo?.CheckAfterSeconds, 0)
                Console.WriteLine($"Twitter video testing in progress - waiting {checkAfterSeconds} seconds.")
                Await Task.Delay(checkAfterSeconds * 1000)
            End If
            mediaStatusResponse = Await (From stat In twitterCtx.Media Where stat.Type = MediaType.Status AndAlso stat.MediaID = media.MediaID Select stat).SingleOrDefaultAsync()


        Loop While mediaStatusResponse?.ProcessingInfo?.State = MediaProcessingInfo.InProgress

        If mediaStatusResponse?.ProcessingInfo?.State = MediaProcessingInfo.Succeeded Then
            Dim tweet22 As Status = Await twitterCtx.TweetAsync(status.Trim, New ULong() {media.MediaID})
            If tweet22 IsNot Nothing Then Console.WriteLine($"Tweet sent: {tweet22.Text}")
        Else
            Dim [error] As MediaError = mediaStatusResponse?.ProcessingInfo?.[Error]
            If [error] IsNot Nothing Then Console.WriteLine($"Request failed - Code: {[error].Code}, Name: {[error].Name}, Message: {[error].Message}")
        End If
    End Function

The difference was that I used `=` instead of `is` for checking `MediaProcessingInfo.Succeeded`.

**Comment by geziri** [comment]
Hi
thank you 
it's working
