### ISSUE TITLE
ChooseAuthenticationStrategy 

### ISSUE THREAD

**Issue by matt2323** [JoeMayo/LinqToTwitter#206]
Hello, 
I ran into a minor issue with ChooseAuthenticationStrategy. 

 The ConsoleKey enum has both a D1 and a NumPad1. 

Maybe something like this instead? 
            IAuthorizer auth = input.Key switch
            {
                ConsoleKey.D1 => DoPinOAuth(),
                ConsoleKey.NumPad1 => DoPinOAuth(),
                ConsoleKey.D2 => DoApplicationOnlyAuth(),
                ConsoleKey.NumPad2 => DoApplicationOnlyAuth(),
                ConsoleKey.D3 => DoSingleUserAuth(),
                ConsoleKey.NumPad3 => DoSingleUserAuth(),
                ConsoleKey.D4 => DoXAuth(),
                ConsoleKey.NumPad4 => DoXAuth(),
                _ => DoPinOAuth(),
            };

It took me longer that I care to admit to figure out why I had to keep entering a pin :) 

Thanks 
Matt

**Comment by matt2323** [comment]
I should add this would be in... 
LinqToTwitter-main\Samples\LinqToTwitter6\Console\ConsoleDemo.CSharp\ConsoleDemo.CSharp\OAuth.cs

**Comment by JoeMayo** [comment]
Thanks for noticing that - you're welcome to do a PR on it. BTW, don't know if `ConsoleKey.D1 | ConsoleKey.NumPad1 => DoPinOAuth()` would work too.

**Comment by matt2323** [comment]
Sure thing! 
Looks like ConsoleKey.D1 | ConsoleKey.NumPad1 doesn't work, not really sure why. 
Looks like we can use the keychar though. 

            IAuthorizer auth = input.KeyChar switch
            {
                '1' => DoPinOAuth(),
                '2' => DoApplicationOnlyAuth(),
                '3' => DoSingleUserAuth(),
                '4' => DoXAuth(),
                _ => DoPinOAuth(),
            };

**Comment by JoeMayo** [comment]
Thanks Matt - looks good - verified and merged.
