### ISSUE TITLE
ListType.Ownerships throws error when querying lists

### ISSUE THREAD

**Issue by erraineon** [JoeMayo/LinqToTwitter#214]
I'm using LinqToTwitter 6.3.0 through Nuget with the following code:
```
var lists = await twitterContext.List
    .Where(list => list.Type == ListType.Ownerships &&
                   list.UserID == userId)
    .ToListAsync();
```
Where `userId` is an external parameter. The error I get is:
```
System.InvalidOperationException: The requested operation requires an element of type 'Array', but the target element has type 'Object'.
```

From peeking at the source code it seems that `ListRequestProcessor` uses `HandleMultipleListsResponse` whereas the [official API documentation](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/create-manage-lists/api-reference/get-lists-ownerships) claims that the returned value will be an object and the lists themselves will be a value on that object.

**Comment by JoeMayo** [comment]
Hi,

Thanks for reporting. I can reproduce and am looking at it.

Joe

**Comment by JoeMayo** [comment]
That's fixed and checked in. The same problem with listing memberships and subscriptions. I'll push a new version early next week.

Thanks again,

Joe

**Comment by JoeMayo** [comment]
Just an update - I'm adding a couple new endpoints that I want to deploy at the same time as this. So it will be a couple more days before I push a new version.

**Comment by JoeMayo** [comment]
Released and pushed to NuGet: http://bit.ly/35V1DI6
