### ISSUE TITLE
ASP.NET Core - OAuth Error

### ISSUE THREAD

**Issue by aneillans** [JoeMayo/LinqToTwitter#218]
Issue running the sample code for ASP.NET Core; LinqToTwitter6

Encountering this; worked with previous 5.1.3 code, but not the latest.

System.MissingMethodException: Method not found: 'System.String LinqToTwitter.OAuth.AuthorizerBase.ParseVerifierFromResponseUrl(System.String)'.
   at LinqToTwitter.AspNetAuthorizer.CompleteAuthorizeAsync(Uri responseUrl)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at LinqToTwitter.AspNetAuthorizer.CompleteAuthorizeAsync(Uri responseUrl)

**Comment by JoeMayo** [comment]
Thanks for posting. I'll have to review and see what's happening.

**Comment by JoeMayo** [comment]
I'm not able to repro this. Does my sample work for you?

https://github.com/JoeMayo/LinqToTwitter/tree/main/Samples/LinqToTwitter6/ASP.NET/LinqToTwitter.MVC.CSharp

**Comment by JoeMayo** [comment]
Just a thought - make sure you're adding the LinqToTwitter.AspNet package. I separated them in this version.
