### ISSUE TITLE
403 error on status

### ISSUE THREAD

**Issue by neilhighley** [JoeMayo/LinqToTwitter#22]
Hi, I noticed you updated the new linqttwitter to fix this issue, but this issue also happens on .net 4.0 also. Any chance of an update to the 2.1.1 version that supports 4.0?

https://twittercommunity.com/t/missing-required-parameter-status/11648/7

**Comment by JoeMayo** [comment]
I'm personally working on v4.0, but will accept pull requests for older versions.
