### ISSUE TITLE
Userlookup not working

### ISSUE THREAD

**Issue by AsianPotato** [JoeMayo/LinqToTwitter#222]
When I try to do this query I get an exception. Is it something to do with trying to do an old  twitter api v1 query? 
```
var userResponse =
                            await
                            (from user in service.User
                             where user.Type == UserType.IdLookup &&
                                   user.UserIdList == UserIdLookupString &&
                                   user.TweetMode == TweetMode.Extended
                             select user)
                            .ToListAsync();
```
                           
```
{"ClassName":"System.InvalidOperationException","Message":"The default case of BuildUrl should never execute because a Type must be specified.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at LinqToTwitter.UserRequestProcessor`1.BuildUrl(Dictionary`2 parameters)\r\n   at LinqToTwitter.TwitterContext.ExecuteAsync[T](Expression expression, Boolean isEnumerable)\r\n   at LinqToTwitter.Provider.TwitterQueryProvider.ExecuteAsync[TResult](Expression expression)\r\n   at LinqToTwitter.TwitterExtensions.ToListAsync[T](IQueryable`1 query)\r\n
```

**Comment by JoeMayo** [comment]
Hi,

LINQ to Twitter is in transition between Twitter API v1 and v2. LINQ to Twitter v6.x supports v2 and I'm moving new v2 endpoints from the `User` to the `TwitterUser` entity group. You can fix this like this:

         TwitterUserQuery? userResponse =
                await
                (from user in twitterCtx.TwitterUser
                 where user.Type == UserType.IdLookup &&
                       user.Ids == UserIdLookupString
                 select user)
                .SingleOrDefaultAsync();

Here's the demos:

https://github.com/JoeMayo/LinqToTwitter/blob/main/Samples/LinqToTwitter6/Console/ConsoleDemo.CSharp/ConsoleDemo.CSharp/UserDemos.cs

and docs:

https://www.linqtotwitter.com/LINQ-to-Twitter-6/Users/Lookup-by-ID.html

Joe

**Comment by AsianPotato** [comment]
Unfortunately the users from the API V2 endpoint don't have a status object, I'll stick to using the old version for now I guess.
