### ISSUE TITLE
Is there a way to use the Twitter guest API for authentication

### ISSUE THREAD

**Issue by ahmad-rzk** [JoeMayo/LinqToTwitter#223]
Twitter API supports acquiring a `x-guest-token` from the following endpoint `https://api.twitter.com/1.1/guest/activate.json` without the need for OAuth 

I couldn't find any reference for the guest authentication method, is there a way to achieve this?

**Comment by JoeMayo** [comment]
Hi, 

I don't recall seeing that before. Do you have a URL for where that endpoint is defined?

Joe

**Comment by ahmad-rzk** [comment]
Thank you for your replay Joe,

As it turned out even though this endpoint exists and usable it is not mentioned in the official documentation, devs who are using this endpoint knew about it by reverse-engineering the Twitter web app.

This repo is a straightforward example of this endpoint usage [twitter2mp4](https://github.com/f-rog/twitter2mp4)
