### ISSUE TITLE
LinqToTwitter v5.0 - Error while using in Sitecore ASP.NET MVC Application

### ISSUE THREAD

**Issue by AmitKumar-AK** [JoeMayo/LinqToTwitter#224]
Hi Team,

I am trying to use LinqToTwitter v5.0 in .NET Framework 4.6.1 using ASP.NET MVC project in Sitecore CMS:

`
      public ActionResult GetTwitterJson()
        {
            try
            {
                    var auth = new SingleUserAuthorizer
                    {
                        CredentialStore = new InMemoryCredentialStore()
                        {
                            ConsumerKey = "",
                            ConsumerSecret = "",
                            OAuthToken = "",
                            OAuthTokenSecret = ""
                        }

                    };

                    var twitterCtx = new TwitterContext(auth);
                    var ownTweets = new List<Status>();

                    var statusResponse = new List<Status>();
                    statusResponse = (from tweet in twitterCtx.Status
                                      where tweet.Type == StatusType.User
                                      && tweet.ScreenName == "Sitecore"
                                      && tweet.Count == 10
                                      select tweet).ToList();
                    if (statusResponse.Count > 0)
                    {
                        ownTweets.AddRange(statusResponse);
                    }

                    // Serialize twitter tweets instance into json string
                    return new EmptyResult();
                
            }
            catch (Exception ex)
            {
                
            }

            return this.Json(null);
        }
`

**Error Details:**
   -	Inner Exception:	{"Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."}
   -    Message:  "The underlying connection was closed: An unexpected error occurred on a send."
  -    Stack Trace:  at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at LinqToTwitter.TwitterQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

Am i missing something in the above function call?

**Newtonsoft.Json.dll version is 6.0.8.1811**

_The same code base working in normal ASP.NET MVC application and Window Console but not in Sitecore ASP.NET MVC application._

**Comment by JoeMayo** [comment]
I've seen that error associated with TLS security. The Twitter API uses TLS 1.2. Does adding this to your startup code help:

    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by AmitKumar-AK** [comment]
@JoeMayo: Thanks for the quick help. By adding above line as a first statement in controller:
   public ActionResult GetTwitterJson()
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
