### ISSUE TITLE
TweetMedia.PreviewImageUrl is always null

### ISSUE THREAD

**Issue by karamem0** [JoeMayo/LinqToTwitter#228]
I want to use Twitter Recent Search API (v2.0) via `TwitterContext.TwitterSearch`. The code is below:

```
var search = await this.context
    .TwitterSearch
    .Where(search => search.Type == SearchType.RecentSearch)
    .Where(search => search.Query == "something")
    .Where(search => search.MaxResults == 100)
    .Where(search => search.TweetFields == TweetField.AllFieldsExceptPermissioned)
    .Where(search => search.Expansions == ExpansionField.AllTweetFields)
    .Where(search => search.MediaFields == MediaField.AllFields)
    .Where(search => search.UserFields == UserField.AllFields)
    .SingleAsync();
```

Also I want to get media data from tweet. But `TwitterSearch.Includes.Media.PreviewImageUrl` is always null.
I try to call the API directly, the response JSON is like below:

```
"media": [
    {
        "type": "photo",
        "height": 1151,
        "width": 1920,
        "media_key": "3_...",
        "url": "https://pbs.twimg.com/media/....jpg"
    }
]
```

The property of preview image URL is not `preview_image_url` but `url`. Is `preview_image_url` correct?

**Comment by layinka** [comment]
Experiencing the same thing

**Comment by JoeMayo** [comment]
Just getting back to this. I found that Twitter is only returning `preview_image_url` for types `animated_gif` and `video`. Strangely, they're returning `url` for type `photo`. I have a question out to them on why this is. If I don't hear back from them before the next release, I can add a `Url` property to `TweetMedia` for `TweetMediaType.Photo`.

**Comment by layinka** [comment]
Thanks.

Not entirely sure why twitter did it that way, but thats how it seemed to work.

Hopefully twitter should respond today, so we can get a fix, its really needed

**Comment by layinka** [comment]
Hi @JoeMayo 

Any update please?

**Comment by JoeMayo** [comment]
No answer yet - I have a few API updates to do in the coming week before a new release. If I don't hear back, I'll publish a new release with the URL property. If you can't wait, you can always clone the repository and build the new DLL because that change is already checked in.

**Comment by layinka** [comment]
Hi @JoeMayo ,
Do we have an official release now?
Please push an official release

**Comment by JoeMayo** [comment]
This is deployed now as [LINQ to Twitter v6.8.0](https://www.nuget.org/packages/linqtotwitter/). Sorry it took so long - I was waiting to see if I got an answer and nothing so far. As mentioned earlier, photo and gif URLs show up in the new `Url` field. Just a reminder - I don't know if this will either change in the future or if Twitter will document the actual behavior. Here's
