### ISSUE TITLE
MVC Error Using DLL

### ISSUE THREAD

**Issue by gswiss** [JoeMayo/LinqToTwitter#23]
Hey!  I've just inherited an Umbraco project where LinqToTwitter is leveraged and I am getting the following YSOD error when accessing the CMS if LinqToTwitter.dll is in the /bin directory:

Could not load file or assembly 'System.Web.Mvc, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

If I remove the DLL then the error goes away and I am able to access the CMS but then of course I don't get the mentions that the custom usercontrol writes to the page.  Any ideas on what might cause this apparent MVC version conflict?

Umbraco version is 4.11.5 and the back end works on a few other machines - it is only locally that I am having this problem.  My web.config calls for MVC version 3.0.0.0:

<add assembly="System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />

Thanks,
Garrett

**Comment by JoeMayo** [comment]
There isn't a GitHub release yet, but you can download the DLL from the old CodePlex site: http://linqtotwitter.codeplex.com/releases/view/611378

**Comment by gswiss** [comment]
Perfect-Thanks Joe!  Sorry to bother you with this and thanks for the
package!

 

//Garrett

 

  _____
