### ISSUE TITLE
Possible MEF assembly load issue

### ISSUE THREAD

**Issue by mol** [JoeMayo/LinqToTwitter#24]
When trying to load an assembly that in turn references the LinqToTwitterPcl.dll via the nuget, an error is thrown:

*Could not load file or assembly 'LinqToTwitterPcl, Version=3.1.2.18329, Culture=neutral, PublicKeyToken=957107be965c25d9' or one of its dependencies. The module was expected to contain an assembly manifest.*

The code to load the assembly is:

```c#
var catalog = new AggregateCatalog();

// This fails
catalog.Catalogs.Add(new AssemblyCatalog(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "ContainsReferenceToLTT.dll")));

/* More catalogs are added here */

var container = new CompositionContainer(catalog);
```

This only happens on a few machines out of thousands live as far as I know, and I've so far been unable to reproduce it. I realize it's not much to go on but thought I'd ask just in case :)

The app is targeting .NET 4.5.1 by the way.

**Comment by JoeMayo** [comment]
Hi,

This might not be a MEF issue. L2T has dependencies on RX (several assemblies) and 3 System.Net.Http assemblies. You can look at the source to see what they are and make sure you've deployed those too.

Joe

**Comment by mol** [comment]
Hi Joe,

They're installed along with it via the nuget, and have been deployed. For
the vast majority everything is loaded fine and works, but a few get the
manifest error. I was just wondering if you had heard of others having the
manifest error under some circumstances.

**Comment by mol** [comment]
On further investigation I don't think this is an issue with LinqToTwitter either. I've seen reports of it happening with other components now as well. I think it's an AdvancedInstaller issue instead. I'm going to close the issue. Thanks for the reply :)
