### ISSUE TITLE
.TweetMode == TweetMode.Extended no longer works. :(

### ISSUE THREAD

**Issue by JoeMayo** [JoeMayo/LinqToTwitter#245]
.TweetMode == TweetMode.Extended no longer works. :(

_Originally posted by @rkamaladasa in https://github.com/JoeMayo/LinqToTwitter/issues/100#issuecomment-962662753_

**Comment by JoeMayo** [comment]
Which version of LINQ to Twitter are you using and can you post your query?

**Comment by rkamaladasa** [comment]
version 6.9 according to NuGet
var tweets = 
                (from tweet in twitterContext.Status
                 where tweet.Type == StatusType.User && tweet.ScreenName == username && tweet.TweetMode == TweetMode.Extended
                 select tweet)
                .ToList();

**Comment by JoeMayo** [comment]
Please explain "no longer works". Here's the sample that I just tried:

https://github.com/JoeMayo/LinqToTwitter/tree/main/Samples/LinqToTwitter6/Console/ConsoleDemo.CSharp

BTW, when using `TweetMode == TweetMode.Extended`, are you reading FullText?

**Comment by rkamaladasa** [comment]
It was throwing a compiler error. I figured it out though; had to use LinqToTwitter.Common.TweetMode.Extended as I wasn't using the Common namespace. Thanks for the help - the FullText was also missing.

**Comment by JoeMayo** [comment]
Great to hear - hope you are successful with LINQ to Twitter.

[@JoeMayo](https://twitter.com/JoeMayo)
