### ISSUE TITLE
No support for video

### ISSUE THREAD

**Issue by damien-raemy-ift** [JoeMayo/LinqToTwitter#27]
Hello,

I want to use your library to retreive all informations about my tweets. I can get text, images, hashtags, but not video URLs. I searched but I don't find how to find extended_entities/video_info, like documented in https://dev.twitter.com/overview/api/entities-in-twitter-objects#extended_entities

Thanks

**Comment by JoeMayo** [comment]
Hi,

I just added video uploads and checked into source control:

https://github.com/JoeMayo/LinqToTwitter/wiki/Uploading-And-Tweeting-Media

Joe

**Comment by Talmis** [comment]
Hi Joe,

Is it possible to retrieve the video / animated gif information from an existing tweet using LinqToTwitter?

Thanks

Ross

**Comment by JoeMayo** [comment]
Hi Ross,

Yes, each Status has an ExtendedEntities property with MediaEntities that can contain a url if a tweet has a video.

Joe

**Comment by bj-eit** [comment]
Hi Joe,
I am using LinqToTwitter library for getting Tweets Like by User. I am getting all properties of tweet except below :

"video_info": {
				"aspect_ratio": [
					15,
					11
				],
				"duration_millis": 5750,
				"variants": [{
					"content_type": "application/x-mpegURL",
					"url": "https://video.twimg.com/ext_tw_video/661820161100398592/pu/pl/Dfjzq1Cb2GGCN-t2.m3u8"
				}, {
					"bitrate": 320000,
					"content_type": "video/webm",
					"url": "https://video.twimg.com/ext_tw_video/661820161100398592/pu/vid/244x180/NoQJN7xFNbZ-Auu4.webm"
				}, {
					"bitrate": 320000,
					"content_type": "video/mp4",
					"url": "https://video.twimg.com/ext_tw_video/661820161100398592/pu/vid/244x180/NoQJN7xFNbZ-Auu4.mp4"
				}, {
					"content_type": "application/dash+xml",
					"url": "https://video.twimg.com/ext_tw_video/661820161100398592/pu/pl/Dfjzq1Cb2GGCN-t2.mpd"
				}]
			}

Please help me how can I fetch above Tweet details from LinqToTwitter library as in current version of 3.1.2 its not supported.

Thanks,
Bipin

**Comment by JoeMayo** [comment]
Hi Bipin,

The TwitterContext has a RawResult property that contains the JSON of the most recent tweet. I'm currently working on v4.0, but will accept pull-requests for earlier versions.

Joe

**Comment by bj-eit** [comment]
Thanks. 
Shall I expect **video_info** (Which is must needed in case of Video and GIF file in Tweet) entity will be added in **Status.cs** class in newer version?

**Comment by bj-eit** [comment]
Hi Joe,
I am fetching Tweets liked by user and I am getting list of **Favourites** object. 
Is there any way to get RAW JSON of each liked tweet?
