### ISSUE TITLE
'CoutryCode' instead of 'CountryCode' in PlaceField.cs

### ISSUE THREAD

**Issue by JeepNL** [JoeMayo/LinqToTwitter#271]
'CoutryCode' instead of 'CountryCode' in PlaceField.cs (line 28)

see: https://github.com/JoeMayo/LinqToTwitter/blob/bef19b8fab83b36a6262cf8d8cba22421bd0623a/src/LinqToTwitter6/LinqToTwitter/Common/FieldEnums/PlaceField.cs#L28

**Comment by JoeMayo** [comment]
Fixed - thanks
