### ISSUE TITLE
"Id" missing in L2T v6 TweetEntityMention, bug or intentional?

### ISSUE THREAD

**Issue by JeepNL** [JoeMayo/LinqToTwitter#276]
In `TweetEntityMention.cs` the `Id` property is missing. I don't know if this is a bug or intentional.  For a lookup I can use the `Username` as well.

See:
https://github.com/JoeMayo/LinqToTwitter/blob/bef19b8fab83b36a6262cf8d8cba22421bd0623a/src/LinqToTwitter6/LinqToTwitter/Tweet/TweetEntityMention.cs#L8

JSON from Twitter: 

	"mentions": [
	  {
		"start": 112,
		"end": 124,
		"username": "internet_nl",
		"id": "2536668400"
	  }
	]

**Comment by JoeMayo** [comment]
It's a bug - we should be returning all the data.
