### ISSUE TITLE
L2T v6 'Includes/Poll' fields missing?

### ISSUE THREAD

**Issue by JeepNL** [JoeMayo/LinqToTwitter#277]
I think that L2T `TweetType.TweetsTimeline` doesn't return the (includes/)poll fields. See below for the query I'm using. But maybe there's something wrong with my query ... 

Is it missing here? https://github.com/JoeMayo/LinqToTwitter/blob/9226cefe3a72b69f7a6052ac47ac44f5aa07936e/src/LinqToTwitter6/LinqToTwitter/Common/TwitterInclude.cs#L6

I've a sample tweet, ID = 1508426492824408066, my Twitter UserId = 47907871

Twitter returns [this JSON](https://oauth-playground.glitch.me/?id=findTweetsById&params=%28%27quVy%21%28%27LWzYG37035677698%2CG43339741184%2CG46120540165%27%29%7Ebody%21%28%29%7Epath%21%28%29%7EzY1508426492824408066WusVANJprofileIsVJTvVifie*proOcO*urlB-pXned_P_NlocaF%2CK-descripF%2CUtWLQEs.R_key-Cs.NCs.z.Qr_NKs.menFs.usVJHEs.poll_z-geo.S_zWRApreviewIrl%2CtypDR_key%2Calt_OxMj-heighMwzthBsWPAQE-K-NHr_Nlang%2CC-reply_settXg-OxMsourcDUMconvVsaF_NgeoB-Tpossibly_sensitivDconOxt_annotaFsWSAZ_codDZ%2Cfull_Jgeo%2CNJcontaXed_withX%2CS_typeWpollANopF-votXg_statu-end_daOtimDjXuOs%27%29*d%2C-s%2CA.fieldYB%2Cpublic_metricCrefVenced_PDe%2CEr_NattachmentFtionG14603237HX_reply_to_useI_image_url%2CuJnamDKentitieLexpansionYMt%2CNi*OtePtweetQauthoRmediaSplaceTwithhel*UcreaOd_aVerW%27%7EXinYs%21%27ZcountryjduraF_mzid%01zjZYXWVUTSRQPONMLKJIHGFEDCBA-*_) code at Twitter Playground (you need to run it, for a result)

**My L2T Query**:

		TweetQuery? tweetQuery = await (
				from tweet in twitterCtx.Tweets
				where tweet.Type == TweetType.TweetsTimeline
					&& tweet.Expansions ==
						$"{ExpansionField.MediaKeys}," +
						$"{ExpansionField.AuthorID}," +
						$"{ExpansionField.ReferencedTweetID}," +
						$"{ExpansionField.ReferencedTweetAuthorID}," +
						$"{ExpansionField.MentionsUsername}," +
						$"{ExpansionField.InReplyToUserID}," +
						$"{ExpansionField.PollIds}," +
						$"{ExpansionField.PlaceID}"
					&& tweet.ID == "47907871" // tweet.ID = Tweet AuthorId, not the id of the tweet.
					&& tweet.UserFields == $"{UserField.AllFields}"
					&& tweet.TweetFields == $"{TweetField.AllFieldsExceptPermissioned}"
					&& tweet.MediaFields == $"{MediaField.AllFieldsExceptPermissioned}"
					&& tweet.PlaceFields == $"{PlaceField.AllFields}"
					&& tweet.PollFields == $"{PollField.AllFields}"
					&& tweet.MaxResults == 5
				select tweet
		).SingleOrDefaultAsync();

My L2T query doesn't return the `includes/polls` fields (from the Twitter Playground result), ie: 
```
  "includes": {
    "polls": [
      {
        "end_datetime": "2022-04-04T12:50:15.000Z",
        "voting_status": "open",
        "options": [
          {
            "position": 1,
            "label": "Yes",
            "votes": 0
          },
          {
            "position": 2,
            "label": "No",
            "votes": 1
          },
          {
            "position": 3,
            "label": "Not Sure",
            "votes": 1
          },
          {
            "position": 4,
            "label": "See results",
            "votes": 0
          }
        ],
        "duration_minutes": 10079,
        "id": "1508426492107239427"
      }
    ],
```

**Comment by JoeMayo** [comment]
Thanks - Looks like I didn't add that at all. 

BTW, nice implementation of C# interpolated strings for expansions/fields.

**Comment by JeepNL** [comment]
Thank you! For the fields (in this example) it isn't really necessary, because I'm using 'AllFields' and not a selection (where you need a comma separator). 

The Twitter Tweet 'CashTag' object is also not (yet) implemented in L2T. It's exactly the same as the HashTag only with "$" in front of it instead of "#"  and it's used for stock symbols. It's not much used, but it's in the API v2 Tweet model specification.  So maybe you want to add it too? And maybe I should I create a new issue for this?

Your TweetEntitities object:

https://github.com/JoeMayo/LinqToTwitter/blob/bef19b8fab83b36a6262cf8d8cba22421bd0623a/src/LinqToTwitter6/LinqToTwitter/Tweet/TweetEntities.cs#L9

Twitter docs: [Tweet Object Model](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet) (Tweet/Entities/CashTags)

More info about the CashTag: [The S&P 500 Twitter Sentiment Index](https://developer.twitter.com/en/use-cases/build-for-businesses/sp-500-twitter-sentiment-index)

**Comment by JoeMayo** [comment]
Note - The Poll Object:

https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/poll
