### ISSUE TITLE
'ICredentialStore' does not contain a definition for 'AccessToken'

### ISSUE THREAD

**Issue by kevin-shelaga** [JoeMayo/LinqToTwitter#284]
Latest version 6.14.0 following example here: https://github.com/JoeMayo/LinqToTwitter/blob/914f6c2cad4298dd075ac1e98bf0daa67a1fb87e/Samples/LinqToTwitter6/Console/ConsoleDemo.CSharp/ConsoleDemo.CSharp/OAuth.cs#L82

Exact same problem with AccessTokenSecret as well.

```
                var auth = new SingleUserAuthorizer();
                auth.CredentialStore = new SingleUserInMemoryCredentialStore();
                auth.CredentialStore.ConsumerKey = Environment.GetEnvironmentVariable("TwitterConsumerKey");
                auth.CredentialStore.ConsumerSecret = Environment.GetEnvironmentVariable("TwitterConsumerSecret");
                auth.CredentialStore.AccessToken = Environment.GetEnvironmentVariable("TwitterAccessToken");
                auth.CredentialStore.AccessTokenSecret = Environment.GetEnvironmentVariable("TwitterAccessTokenSecret");
                await auth.AuthorizeAsync();

                var twitterCtx = new TwitterContext(auth);
```

**Comment by JeepNL** [comment]
Did you download the source of L2T and tried to compile the ConsoleDemo.CSharp sample? Does it compile?

**Comment by kevin-shelaga** [comment]
I haven't tried yet, I can try that this morning

**Comment by JeepNL** [comment]
I just downloaded it and it does compile. You'll need to install at least .NET SDK 5, better is [.NET SDK 6](https://dotnet.microsoft.com/en-us/download) (I tested it with .NET 7 preview 3)

If you download it change your `ConsoleDemo.CSharp.csproj` to (

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework> // (NOTE: change to the SDK you've installed, so 5, 6 or 7)
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="LinqToTwitter" Version="6.14.0" />
	</ItemGroup>

  <!--<ItemGroup>
	  <ProjectReference Include="..\..\..\..\..\src\LinqToTwitter6\LinqToTwitter\LinqToTwitter.csproj" />
	</ItemGroup>-->

</Project>
```

With .NET 7 Preview 3 I saw a couple of other, non related, errors (spaces/search), but I just commented them out. The error you mentioned doesn't show up.

![Screenshot 2022-04-22 144930](https://user-images.githubusercontent.com/39458532/164717622-a74937ab-ef46-472e-b5d0-b432db4ebda9.jpg)

**Comment by kevin-shelaga** [comment]
Strange because I am using .net 6 and things do not compile for me. I will be downloading the sample now to test.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="linqtotwitter" Version="6.14.0" />
```

**Comment by kevin-shelaga** [comment]
@JeepNL It looks like the issue might be that im using .net6 aspnetcore webapi. The samples for ASP.NET do not use access token. When I try to use the samples and add in access token it fails to compile, which is the same thing I am seeing.

**Comment by JeepNL** [comment]
@kevin-shelaga I tink your code (`SingleUserAuthorizer`) should also work in a ASP.NET Web API. Maybe you can try it with this Nuget package https://www.nuget.org/packages/LinqToTwitter.AspNet/ - If that doesn't solve the problem, could you share more of your code so I can see what's possibly going wrong?

**Comment by kevin-shelaga** [comment]
Same thing with `LinqToTwitter.AspNet` and to reiterate I see the same thing with the provided samples with the ASP.NET sample if you try to change to singleUser auth and add in accessToken here: https://github.com/JoeMayo/LinqToTwitter/blob/914f6c2cad4298dd075ac1e98bf0daa67a1fb87e/Samples/LinqToTwitter6/ASP.NET/LinqToTwitter.MVC.CSharp/LinqToTwitter.MVC.CSharp/Controllers/OAuthController.cs#L26


My code is very simple, im migrating from TweetInvi to LinqToTwitter

csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="linqtotwitter.AspNet" Version="6.14.0" />
...
```

service
```
 public async Task<string> VerifyScreenNameAsync(string screen_name)
        {
            string result = null;

            try
            {
                var auth = new SingleUserAuthorizer();
                auth.CredentialStore = new SingleUserInMemoryCredentialStore();
                auth.CredentialStore.ConsumerKey = Environment.GetEnvironmentVariable("TwitterConsumerKey");
                auth.CredentialStore.ConsumerSecret = Environment.GetEnvironmentVariable("TwitterConsumerSecret");
                auth.CredentialStore.AccessToken = Environment.GetEnvironmentVariable("TwitterAccessToken");     <---- error here
                auth.CredentialStore.AccessTokenSecret = Environment.GetEnvironmentVariable("TwitterAccessTokenSecret");      <---- error here
                await auth.AuthorizeAsync();

                var twitterCtx = new TwitterContext(auth);
...
```

**Comment by JeepNL** [comment]
Okay, I can reproduce the error in the MVC sample. I need to think about this ...

**Comment by JeepNL** [comment]
Please try this:

```
var auth = new SingleUserAuthorizer
{
	CredentialStore = new SingleUserInMemoryCredentialStore()
	{
		ConsumerKey = Environment.GetEnvironmentVariable("TwitterConsumerKey"),
		ConsumerSecret = Environment.GetEnvironmentVariable("TwitterConsumerSecret"),
		AccessToken = Environment.GetEnvironmentVariable("TwitterAccessToken"),
		AccessTokenSecret = Environment.GetEnvironmentVariable("TwitterAccessTokenSecret")
	}
};

var twitterCtx = new TwitterContext(auth);
```
![Screenshot 2022-04-23 183547](https://user-images.githubusercontent.com/39458532/164915057-8ec427ba-31df-4828-94c4-c0c5b883b2c3.jpg)

**Comment by kevin-shelaga** [comment]
Looks like that worked, well it compiles now but I get errors from twitter. Looks like they are having issues https://api.twitterstat.us

What was the underlying issue?

**Comment by JeepNL** [comment]
Glad it worked! As for the underlying issue, I looked at your code and my first thought too was that it should work, but it didn't. The syntax was wrong.
