### ISSUE TITLE
Truncating status to 140 chars

### ISSUE THREAD

**Issue by steveloft** [JoeMayo/LinqToTwitter#29]
Sorry if this is in the wrong place, it's not an issue as such, it's a query. If I want to make sure that a status update does not exceed 140 chars, is it sufficient to check the length of my C# string and truncate that to 140 chars if necessary, before calling TweetAsync? Does that allow for any encoding that may or may not happen after I've called TweetAsync?

**Comment by JoeMayo** [comment]
Hi,

Here's a link to Twitter's Character Counting rules:

https://dev.twitter.com/overview/api/counting-characters

One of the things you should be aware of is that their URL shortening service t.co has different rules for the length of the URL in the tweet.

Joe
