### ISSUE TITLE
Incorrect url for StatusType.Show

### ISSUE THREAD

**Issue by RyanFromIT** [JoeMayo/LinqToTwitter#30]
Twitters API requires this request to only have the Tweets ID and is not appended to the url as the code currently does.

Example:

Currently:
https://api.twitter.com/1.1/statuses/show.json?ID=657248345937743872

Should be:
https://api.twitter.com/1.1/statuses/show/657248345937743872.json

Idea of change:

StatusRequestProcessor.cs

Line 263:
return BuildUrlParameters(parameters, "statuses/show.json");

Change to:
if (!parameters.ContainsKey("ID"))
    throw new ArgumentException("ID is a required parameter for Show request");
return new Request(string.Format(@"{0}statuses/{1}.json", BaseUrl, parameters["ID"]));

**Comment by JoeMayo** [comment]
Thanks for the feedback. The current implementation is consistent with Twitter API documentation and it works:

https://dev.twitter.com/rest/reference/get/statuses/show/%3Aid
