### ISSUE TITLE
Auth Error unless I use specific permissions

### ISSUE THREAD

**Issue by HappyCatKitten** [JoeMayo/LinqToTwitter#309]
### Please let us know what you use:

- .NET SDK version:
6.0 core

- LINQ To Twitter Version:
6.14.0

### Describe the issue
Unless I use these three permissions I get an exception

`                    "users.read",
                    "offline.access",
                    "tweet.read"`

### Error / Console Output

**If I dont use offline.access I get:**

ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')

**If I dont use users.read I get:**

TwitterQueryException: Unhandled Error - LINQ to Twitter wasn't able to parse Twitter error message. Please copy this message, with the Detail property contents and the query you were using (how to reproduce) to Joe Mayo at https://github.com/JoeMayo/LinqToTwitter/issues.
LinqToTwitter.Net.TwitterErrorHandler.BuildAndThrowTwitterQueryException(string responseStr, HttpResponseMessage msg)
LinqToTwitter.Net.TwitterErrorHandler.HandleGenericErrorAsync(HttpResponseMessage msg)
LinqToTwitter.Net.TwitterErrorHandler.ThrowIfErrorAsync(HttpResponseMessage msg)
LinqToTwitter.Provider.TwitterExecute.HandleResponseAsync(HttpResponseMessage msg)
LinqToTwitter.Provider.TwitterExecute.QueryTwitterAsync<T>(Request request, IRequestProcessor<T> reqProc)
LinqToTwitter.TwitterContext.ExecuteAsync<T>(Expression expression, bool isEnumerable)
LinqToTwitter.Provider.TwitterQueryProvider.ExecuteAsync<TResult>(Expression expression)
LinqToTwitter.TwitterExtensions.SingleOrDefaultAsync<T>(IQueryable<T> query)
Midnight.Web.Controllers.TwitterAuthController.CompleteAsync() in TwitterAuthController.cs
+
        var response = await (

Here is the code:

`    public async Task<ActionResult> BeginAsync()
    {
        // get the referring url
        var referrer = Request.GetDisplayUrl();

        var twitterCallbackUrl =
            Request.GetDisplayUrl().Replace("Begin", "Complete", true, CultureInfo.InvariantCulture);

        var auth = new MvcOAuth2Authorizer
        {
            CredentialStore = new OAuth2SessionCredentialStore(HttpContext.Session)
            {
                ClientID = TwitterFetch.clientID,
                ClientSecret = TwitterFetch.secret,
                Scopes = new List<string>
                {
                    "users.read",
                    "offline.access",
                    "tweet.read"
                },
                RedirectUri = twitterCallbackUrl
            }
        };

        return await auth.BeginAuthorizeAsync("MyState");
    }

    public async Task<ActionResult> CompleteAsync()
    {
        var auth = new MvcOAuth2Authorizer
        {
            CredentialStore = new OAuth2SessionCredentialStore(HttpContext.Session)
        };

        Request.Query.TryGetValue("code", out var code);
        Request.Query.TryGetValue("state", out var state);

        await auth.CompleteAuthorizeAsync(code, state);`

The error occurs after the callback on the line:

`await auth.CompleteAuthorizeAsync(code, state);`

**Comment by JoeMayo** [comment]
Hi HappyCatKitten,

Thanks for reporting. I'm still chasing different error formats and this helps.

Regards,

Joe

**Comment by HappyCatKitten** [comment]
Cool. I'm happy to help resolve this bug. 

Usual story "its urgent as I have project to launch" :)

let me know if you would like to work together to find a solution! (I really do have a project to launch) haha

Thanks for your great work Joe!

**Comment by JeepNL** [comment]
Just FYI, when looking at the Twitter API V2 Docs ([example](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets)) the OAuth 2.0 scopes `tweet.read` _and_ `users.read`  are required for most V2 endpoints.

**Comment by JoeMayo** [comment]
Just completed a PR for this - Thanks for reporting.
