### ISSUE TITLE
Document Exception

### ISSUE THREAD

**Issue by JoeMayo** [JoeMayo/LinqToTwitter#32]
API calls contain validations on input parameters that throw exceptions. The documentation doesn't cover these cases. The closest thing that exists is to declare whether a parameter is required or not. It would be nice to have a table to show these exceptions.

The Wiki is open for modification, so any help in this area is welcome.

**Comment by khaha2210** [comment]
heelo i run test demo sent message  but error The remote server returned an error: (403) Forbidden . can u help me.
