### ISSUE TITLE
Search Tweet By City

### ISSUE THREAD

**Issue by brkzkn** [JoeMayo/LinqToTwitter#35]
Hi,

When i try to search tweet by location, i didn't receive result. I added sample code. Can you show me how can i search tweet by city?

Thank you

[HomeController.zip](https://github.com/JoeMayo/LinqToTwitter/files/72786/HomeController.zip)

**Comment by JoeMayo** [comment]
Hi,

The Search API has a geolocalization parameter:

https://dev.twitter.com/rest/public/search

This Maps to the GeoCode property on the LINQ to Twitter Search entity. Get the coordinates of the middle of the city and specify a GeoCode with a "lat,long,radius" of the area you want to target. You'll want to read the Twitter API search docs to understand the constraints and what to expect in the results.

**Comment by brkzkn** [comment]
Hi John, 

Thank you for reply. Probably, my GeoCode is wrong. How can I get GeoCode for city with Twitter Api?

Do you have any example?

**Comment by JoeMayo** [comment]
Twitter supports a set of \geo endpoints that you can use. Here's the LINQ to Twitter support for those:

https://github.com/JoeMayo/LinqToTwitter/wiki/Getting-Geographical-Information

You might have to experiment a bit to find which gives you better results, but it sounds like a GeoType.Search query might be a good place to start. I believe the documentation states that this is based on the Yahoo Places API. Each of the LINQ to Twitter documentation pages has a link at the bottom where you can trace back to the matching Twitter API endpoint for more details on the parameters.

I also did a quick Bing search and found this: which might be useful for testing: http://www.latlong.net/ - there are also various mapping APIs, like Bing and Google that might be useful. Yahoo has the Places API too.
