### ISSUE TITLE
How to create a login page?

### ISSUE THREAD

**Issue by Englbach** [JoeMayo/LinqToTwitter#37]
I did not see your code for login page(for clients)?

  {

            var authorizer = new ApplicationOnlyAuthorizer
            {
                CredentialStore = new InMemoryCredentialStore
                {
                    ConsumerKey = api_key,
                    ConsumerSecret = secrect_key
                }
            };
            await authorizer.AuthorizeAsync();

**Comment by JoeMayo** [comment]
Hi,

There are a couple areas where there are demos:

1. Samples has the L2T v4.0 (beta) demos.
2. There are also L2T 3.x demos at: https://github.com/JoeMayo/LinqToTwitter/tree/master/New/Demos

Joe
