### ISSUE TITLE
Request a User’s Email Address 

### ISSUE THREAD

**Issue by prog-moh** [JoeMayo/LinqToTwitter#41]
what about adding option to Request a User’s Email Address  for white listed applications in 

GET account/verify_credentials request options 

as recently twitter allowed to request user's email address 
as described here https://dev.twitter.com/rest/reference/get/account/verify_credentials

**Comment by JoeMayo** [comment]
Thanks for letting me know - It should be added.

**Comment by ericgreenmix** [comment]
With this merged in, could you publish a new Nuget package?

**Comment by JoeMayo** [comment]
I still need to add a couple more items and test a few things before pushing to NuGet again. I know it's been a while and will do as soon as I'm able, but don't have a date for you.

**Comment by JoeMayo** [comment]
Released in v4.0 and deployed to NuGet: https://github.com/JoeMayo/LinqToTwitter/releases/tag/v4.0.0
