### ISSUE TITLE
Problem with SingleUserAuthorizer in Console App

### ISSUE THREAD

**Issue by robertkgaudet** [JoeMayo/LinqToTwitter#45]
I'm trying to use SingleUserAuthorizer  inside of a console application and I'm getting this error. The error is generated when the Linq runs....

--- Exception thrown: 'System.AggregateException' in mscorlib.dll ---

I've tried everything I can think of, what am I doing wrong?

This is the code....
var auth = new SingleUserAuthorizer
{
	CredentialStore = new InMemoryCredentialStore
	{
		ConsumerKey = twitterConsumerKey,
		ConsumerSecret = twitterConsumerSecret,
		OAuthToken = twitterAccessTokenSecret,
			OAuthTokenSecret = twitterAccessToken
	}
};

var twitterCtx = new TwitterContext(auth);

User user = 
(from tweet in twitterCtx.User
	where tweet.Type == UserType.Show &&
		tweet.ScreenName == member.screenName
	select tweet)
.SingleOrDefault();

**Comment by JoeMayo** [comment]
Hi Robert,

Can you share more info on the AggregateException? There is an Exceptions property with more details and you can drill down from there to find the specific exception being raised.

Since you mentioned "Authorizer", I'm thinking there might be an authorization error, though I won't know until I see the exception details. If it is, an HTTP 401 Unauthorized error is common. I've written an entire section in the LINQ to Twitter FAQ to help with those types of problems:

https://github.com/JoeMayo/LinqToTwitter/wiki/LINQ-to-Twitter-FAQ#1-i-get-a-401-unauthorized-exception-how-to-i-figure-out-the-problem

**Comment by robertkgaudet** [comment]
Hey Joe....

I've re-written it slightly to incorporate async... probably not needed since it's just a console application regardless this is where I am with the code and the current error.

've gone back and forth between async and the previous version of the code and gotten the previous error without async and the one below under async... If you would like, I'll quickly rework with the previous non-async and get the AggregateException details and send your way.

Thank you so much for responding. I've used LinqToTwitter on numerous projects... but it's been a while... and I'm just getting familiar with 4.5 and async/await development.




static async Task GetMemberData(IQueryable<Member> members)
{
FPNUpdaterDataContext dc = new FPNUpdaterDataContext();
foreach (var member in members)
{
string twitterUsername = string.Empty;
string name = string.Empty;
string description = string.Empty;
string profileImage = string.Empty;
string status = string.Empty;
string latitude = string.Empty;
string longitude = string.Empty;
int followerCount = 0;
int favoriteCount = 0;
int following = 0;
int retweetCount = 0;
int statusesCount = 0;
string slug = string.Empty;
string result = string.Empty;
//User user;

twitterUsername = member.TwitterUserName;
//Add follower count to count table.
//GetTwitterFollowers(member, out user, out result);


string twitterConsumerKey = ConfigurationSettings.AppSettings["TwitterConsumerKey"];
string twitterConsumerSecret = ConfigurationSettings.AppSettings["TwitterConsumerSecret"];
string twitterAccessTokenSecret = ConfigurationSettings.AppSettings["TwitterAccessTokenSecret	"];//member.oauthTokenSecret;
string twitterAccessToken = ConfigurationSettings.AppSettings["TwitterAccessToken"];// member.oauthToken;

try
{ 
//Credentials = new SingleUserInMemoryCredentials InMemoryCredentials
var auth = new SingleUserAuthorizer
{
CredentialStore = new SingleUserInMemoryCredentialStore
{
ConsumerKey = twitterConsumerKey,
ConsumerSecret = twitterConsumerSecret,
OAuthToken = twitterAccessTokenSecret,
AccessToken = twitterAccessToken
}
};

//await auth.AuthorizeAsync();

var twitterCtx = new TwitterContext(auth);
					
User user = await
(from tweet in twitterCtx.User
where tweet.Type == UserType.Show &&
tweet.ScreenName == member.screenName
select tweet)
.SingleOrDefaultAsync();

if (result == "stop")
{
//We've hit our limit, Twitter wants us to stop.
break;
}

if (user != null)
{
followerCount = user.FollowersCount;
name = user.Name;
description = user.Description;
profileImage = user.ProfileImageUrl.Replace("_normal", "").Replace("_bigger", "");
latitude = user.Status.Coordinates.Latitude.ToString();
longitude = user.Status.Coordinates.Longitude.ToString();
favoriteCount = user.FavoritesCount;
following = user.FriendsCount;
retweetCount = user.Status.RetweetCount;
statusesCount = user.StatusesCount;
slug = user.Slug;

//Update the followercount.
MemberFollowerCount memberFollowerCount = new MemberFollowerCount();

memberFollowerCount.DateUpdated = DateTime.Now;
memberFollowerCount.FollowerCount = followerCount;
memberFollowerCount.MemberFollowerCountId = Guid.NewGuid();
memberFollowerCount.MemberId = member.MemberId;

dc.MemberFollowerCounts.InsertOnSubmit(memberFollowerCount);
dc.SubmitChanges();

//Update member information
var follower = (from f in dc.Members
where f.MemberId == member.MemberId
select f).SingleOrDefault();

if (result == "delete")
{
Console.WriteLine(member.TwitterUserName + ": inactivating user");
follower.IsDeleted = true;
follower.IsInactive = true;
dc.SubmitChanges();
}
else
{
Console.WriteLine(member.TwitterUserName + " " + followerCount + " followers");
follower.FavoriteCount = favoriteCount;
follower.Following = following;
follower.Latitude = latitude;
follower.Longitude = longitude;
follower.RetweetCount = retweetCount;
follower.Slug = slug;
follower.StatusesCount = statusesCount;
follower.Followers = followerCount;
follower.Name = name;
follower.Biography = description;
follower.ProfileImageURL = profileImage;
follower.UpdatedOn = System.DateTime.Now;
follower.Status = status;
dc.SubmitChanges();
}
}
}
catch(Exception ex)
{

}
}
}


ERROR GENERATED WITH ABOVE CODE
"   at LinqToTwitter.ExpressionTreeHelpers.GetValueFromExpression(Expression expression)\r\n   at LinqToTwitter.ExpressionTreeHelpers.GetValueFromEqualsExpression(BinaryExpression be, Type memberDeclaringType, String memberName)\r\n   at LinqToTwitter.ParameterFinder`1.VisitBinary(BinaryExpression be)\r\n   at LinqToTwitter.ExpressionVisitor.Visit(Expression exp)\r\n   at LinqToTwitter.ExpressionVisitor.VisitBinary(BinaryExpression b)\r\n   at LinqToTwitter.ParameterFinder`1.VisitBinary(BinaryExpression be)\r\n   at LinqToTwitter.ExpressionVisitor.Visit(Expression exp)\r\n   at LinqToTwitter.ParameterFinder`1.get_Parameters()\r\n   at LinqToTwitter.UserRequestProcessor`1.GetParameters(LambdaExpression lambdaExpression)\r\n   at LinqToTwitter.TwitterContext.GetRequestParameters[T](Expression expression, IRequestProcessor`1 reqProc)\r\n   at LinqToTwitter.TwitterContext.<ExecuteAsync>d__c4`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at LinqToTwitter.TwitterQueryProvider.<ExecuteAsync>d__6`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at LinqToTwitter.TwitterExtensions.<SingleOrDefaultAsync>d__20`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at TCOTUpdater.Program.<GetMemberData>d__2.MoveNext() in C:\\Users\\Rob Gaudet\\Documents\\Visual Studio 2015\\Projects\\Fizzpop.NinjaUpdateProcess\\Fizzpop.NinjaUpdateProcess\\Program.cs:line 101"

**Comment by robertkgaudet** [comment]
I reworked it back to generate the AggregateException error.... here is the stack trace and some other info.. as well as a screen capture with other messages...


MESSAGE "Object reference not set to an instance of an object."

SOURCE   Source	"LinqToTwitterPcl"	string


{System.Collections.ListDictionaryInternal}


STACK TRACE

"   at LinqToTwitter.ExpressionTreeHelpers.GetValueFromExpression(Expression expression)\r\n   at LinqToTwitter.ExpressionTreeHelpers.GetValueFromEqualsExpression(BinaryExpression be, Type memberDeclaringType, String memberName)\r\n   at LinqToTwitter.ParameterFinder`1.VisitBinary(BinaryExpression be)\r\n   at LinqToTwitter.ExpressionVisitor.Visit(Expression exp)\r\n   at LinqToTwitter.ExpressionVisitor.VisitBinary(BinaryExpression b)\r\n   at LinqToTwitter.ParameterFinder`1.VisitBinary(BinaryExpression be)\r\n   at LinqToTwitter.ExpressionVisitor.Visit(Expression exp)\r\n   at LinqToTwitter.ParameterFinder`1.get_Parameters()\r\n   at LinqToTwitter.UserRequestProcessor`1.GetParameters(LambdaExpression lambdaExpression)\r\n   at LinqToTwitter.TwitterContext.GetRequestParameters[T](Expression expression, IRequestProcessor`1 reqProc)\r\n   at LinqToTwitter.TwitterContext.<ExecuteAsync>d__c4`1.MoveNext()"


![image](https://cloud.githubusercontent.com/assets/7988485/12430911/01f8a2a0-beb8-11e5-954f-a39f4cd65330.png)

**Comment by robertkgaudet** [comment]
![image](https://cloud.githubusercontent.com/assets/7988485/12430934/21108e0a-beb8-11e5-95a7-b380199c3d63.png)

**Comment by robertkgaudet** [comment]
![image](https://cloud.githubusercontent.com/assets/7988485/12430939/33783408-beb8-11e5-92e8-9c409d3411a4.png)

**Comment by JoeMayo** [comment]
Thanks for the extra exception info. Nothing pops out at me for a reason. However, you might be experiencing an async race condition. This can occur if you aren't using async all the way down. e.g. if your program calls an async method without awaiting it's task, the program might end before the async operation completes.

So, make sure that the program calling GetMemberData uses await, something like this:

    await  GetMemberData(members);

and make sure the method that calls that one is awaited, and follow this up the call chain until you read the Main method or an event handler (the event handler will be async void.

Here's my book, C# Succinctly, which is a free download and includes a quick primer on async:

http://www.syncfusion.com/resources/techportal/details/ebooks/csharp

The ConsoleDemos program in the downloadable source code shows how to do this with a console app and there are demos for other technologies too.

**Comment by robertkgaudet** [comment]
Thanks Joe, two quick questions.

1)
Is there anything I need to do prior to actually running the auth scheme? SingleUserAuthorizer in a console app isn't done over SSL..  we don't need a different handshake of any kind before the SingleUserAuthorizer is approved?

2)
Would I have any problems running lots of other users Access Tokens using SingleUserAuthorizer?
IE Twitter isn't looking for only my Access Token right?

I'll download the consoleapp example.

**Comment by JoeMayo** [comment]
1) SingleUserAuthorizer just works because you have all 4 credentials. All LINQ to Twitter communication is via HTTPS.
2) If you have the AccessToken and AccessTokenSecret (synonymous with OAuthToken and OAuthTokenSecret in other authorizers) then just load the values for that user and it will work fine. If you need to initially obtain another user's tokens, you'll need to use one of the other authorizers first. e.g. if you're doing a console app, use a PIN authorizer to obtain OAuthToken/OAuthTokenSecret, and then you can use the SingleUserAuthorizer.

**Comment by robertkgaudet** [comment]
Still working on this Joe.
Good news is I got a valid response with this....
AppSettings below are the access tokens twitter created on my behalf. This works.

var auth = new SingleUserAuthorizer
{
CredentialStore = new SingleUserInMemoryCredentialStore
{
ConsumerKey = twitterConsumerKey,
ConsumerSecret = twitterConsumerSecret,
AccessToken = ConfigurationSettings.AppSettings["TwitterAccessToken"],
AccessTokenSecret = ConfigurationSettings.AppSettings["TwitterAccessTokenSecret"]
}
};

BAD NEWS.....
When I try with a different users tokens in either 'accesstoken'/'accesstokensecret; or 'oauthtoken'/'oauthtokensecret' it breaks with the (Exception thrown: 'System.AggregateException' in mscorlib.dll) error.

Can you explain the difference in the OAuthTokens and AccessTokens below? Is OAuthToken for other users and AccessToken for me only??

var auth = new SingleUserAuthorizer
{
CredentialStore = new SingleUserInMemoryCredentialStore
{
ConsumerKey = twitterConsumerKey,
ConsumerSecret = twitterConsumerSecret,
OAuthToken = twitterAccessToken,
OAuthTokenSecret = twitterAccessTokenSecret,
AccessToken = ConfigurationSettings.AppSettings["TwitterAccessToken"],
AccessTokenSecret = ConfigurationSettings.AppSettings["TwitterAccessTokenSecret"]
}
};

**Comment by JoeMayo** [comment]
OAuthToken and OAuthTokenSecret are the same as AccessToken and AccessTokenSecret. They save in the same property. AccessToken/AccessTokenSecret are just a semantic convenience that matches what Twitter labels them on your application page. Set one set or the other. 

Drill down into the AggregateException to see what the underlying exception is saying. If you set the tokens improperly, you'll get a 401.

**Comment by robertkgaudet** [comment]
It's working... a simple error that was nothing to do with LinqToTwitter...
At least in the trial and error I learned a lot about LTT... thanks Joe.

**Comment by JoeMayo** [comment]
Great - good luck with your project.

**Comment by Marquin777** [comment]
I am having the same error. WHat was the resolution?

**Comment by JoeMayo** [comment]
I don't know what the underlying issue was in his code, but the original query he posted was synchronous, which doesn't work. LINQ to Twitter is async, so you must write async code.
