### ISSUE TITLE
Status.Coordinates should be null if there's no location.

### ISSUE THREAD

**Issue by Pedrazl** [JoeMayo/LinqToTwitter#47]
If a Tweet is no geolocated, coordinates field of his Status should be NULL. Actually the library returns Longitude and Latitude as (0,0), which is a real position. 
This is known as the "NULL ISLAND" pattern.
http://nullisland.com/geography.html

**Comment by JoeMayo** [comment]
Thanks - I'll have a look at how I'm handling that.

**Comment by JoeMayo** [comment]
I looked at this and see what you mean. Changing this would likely break a lot of user's code. So, I added a property IsLocationAvailable that is false when coordinates aren't provided and true when they are.

Committed: https://github.com/JoeMayo/LinqToTwitter/commit/f5ea2e7ace4ebdda3342a29a6cace21890a695f1
