### ISSUE TITLE
Version 4 and MVC

### ISSUE THREAD

**Issue by cadilhac** [JoeMayo/LinqToTwitter#48]
Hi,

Just wanted to try your library to simply authorize my users in an asp.net MVC app. Installed your version 4.0 through nuget and copied your code with the MvcAuthorizer. This class (and more like SessionStateCredentialStore) seems unknown and not in the LinToTwitter namespace. Is the doc in sync? What did I miss?

Thanks

**Comment by JoeMayo** [comment]
Thanks for letting me know. I missed adding the LinqToTwitter.AspNet.dll assembly to the NuGet package. That's fixed now and you can get the latest version 4.1.0 from NuGet and there's a new release here too:

https://github.com/JoeMayo/LinqToTwitter/releases/tag/v4.1.0

I also added a MvcDemo sample to the source code:

https://github.com/JoeMayo/LinqToTwitter/tree/master/Samples/net46/CSharp/AspNetSamples

[Joe Mayo](https://twitter.com/JoeMayo)

**Comment by cadilhac** [comment]
Thank you Joe. A quick question: can I use your code without being linked to owin? I don't use it because of the use of entityframework to store users (I use RavenDb). I have a custom made authorization backend. That's why I use the facebook sdk for .Net to simply authenticate a user with FB and was hoping your code could do the same with Twitter.
