### ISSUE TITLE
Not supported exception when trying to get mentions

### ISSUE THREAD

**Issue by atrauzzi** [JoeMayo/LinqToTwitter#5]
```
{System.NotSupportedException: HttpVersion Http20
   at System.Net.Http.HttpHandlerToFilter.ConvertResponse(HttpResponseMessage rtResponse)
   at System.Net.Http.HttpHandlerToFilter.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.<SendAsync>d__1.MoveNext()}
```

Using the following code:

```
				request = await
					Twitter.Status.Where(tweet =>
						tweet.Type == StatusType.Mentions
						&& tweet.ScreenName == ScreenName
						&& tweet.Favorited == false
					)
					.FirstOrDefaultAsync()
				;
```

**Comment by JoeMayo** [comment]
LINQ to Twitter uses HttpClient, which I thought defaulted to HTTP 1.1. This error is saying the request was made where HttpVersion was set to 2.0. I'm not sure what is happening here and need to do more research. BTW, that query works fine in a .NET 4.5 Console app in Windows 10 - what platform and version are you working on? e.g. Windows Store, phone, asp.net, xamarin, mono, etc.? Any idea why your system is making an HTTP 2.0 request.

**Comment by atrauzzi** [comment]
Not sure, I'm happy to look into anything if you can point me in the right direction.  I was actually running on the recently released Windows 10 IoT on a Raspberry Pi.

I had hoped that maybe there was somewhere for me to flip a default, but I'm still getting up to speed with conventions in C#.  Especially as it pertains to how libraries and system configuration play together.

**Comment by JoeMayo** [comment]
I sent you an email.

**Comment by JoeMayo** [comment]
This must be the same problem as this: https://github.com/JoeMayo/LinqToTwitter/issues/7 

It means I need to upgrade LINQ to Twitter to work with Windows 10. Here's a fork that will currently work with Windows 10:

https://github.com/liquidboy/LinqToTwitter

**Comment by atrauzzi** [comment]
Yeah, I'd agree.  I'll close this for now and we can follow along in the other issue.
