### ISSUE TITLE
invalid media parameter 

### ISSUE THREAD

**Issue by jaganjan** [JoeMayo/LinqToTwitter#51]
when upload videos to twitter i got this error 

Unhandled Exception:

LinqToTwitter.TwitterQueryException: media parameter is invalid.

Exception:

LinqToTwitter.TwitterQueryException: media parameter is invalid.

**Comment by jaganjan** [comment]
iam uploading MP4 File i got media id from upload method but it exception occurs in tweetassync method

**Comment by JoeMayo** [comment]
Hi jaganjan,

There are a couple things you can look at to start debugging:

1. Compare your code to the [UploadVideoAsync method ](https://github.com/JoeMayo/LinqToTwitter/blob/master/Samples/net46/CSharp/ConsoleSamples/StatusDemos.cs)in the sample code. What are the differences? Are you using a different video than the sample?

2. Does your video meet Twitter API guidelines for [Video specifications and recommendations](https://dev.twitter.com/rest/public/uploading-media#videorecs).

3. Look at the media ID returned from the call to `UploadMediaAsync`. Does it look valid?

4. Look at `ctx.ResponseHeaders`after the `UploadMediaAsync`. See if they have any rate-limit info. If you've uploaded too much, which is easy to do in testing, Twitter API will rate-limit your call on that endpoint. The rate-limits are unpublished. If you're rate limited or suspect that might be the case, wait another 24 hours or more and try again.

[@JoeMayo](https://twitter.com/JoeMayo)
