### ISSUE TITLE
Looking for WindowsPhone 8.1 OAuth DEMO

### ISSUE THREAD

**Issue by ulpin** [JoeMayo/LinqToTwitter#52]
Hello,

just wondering if there is a nice OAuth Demo like you have for WindowsPhone and WindowsStore to implement on WindowsPhone 8.1. I just cant get it done by myself to let a user login to twitter.

Cheers

**Comment by JoeMayo** [comment]
Hi,

With Windows Phone 8.1, you have to use a PIN Authorizer. Here's a demo:

https://github.com/JoeMayo/LinqToTwitter/tree/master/New/Demos/Linq2TwitterDemos_WindowsPhone

Also, this requires using LINQ to Twitter v 3.1.2, which is available via NuGet:

https://www.nuget.org/packages/linqtotwitter/3.1.2

[@JoeMayo](https://twitter.com)

**Comment by ulpin** [comment]
Hi Joe,

First of all thank you for your demo, I'm making some progress with it.

Now I'm having some trouble replacing the `OAuthWebBrowser.Navigate` Control. It doesn't seem to be in the linqtotwitter 3.1.2 packacge.

I've tried the following alternatives without success so far:

`GoToTwitterAuthorization = async pageLink =>
                    await Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal,
                   async () => {
                       await Launcher.LaunchUriAsync(new Uri(pageLink, UriKind.Absolute));
                   })`

and

`GoToTwitterAuthorization = async pageLink =>
                await Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal,
               () =>
               {
                   WebAuthenticationBroker.AuthenticateAndContinue(
                new Uri(pageLink, UriKind.Absolute));
               })`

Both examples doesn't lead me to the PIN. Do you know what I could do next?

Cheers, 

Chris

**Comment by JoeMayo** [comment]
The OAuthWebBrowser is a Web control in the OAuth.xaml page. It's designed to take you through the OAuth sequence to authorize your app:

https://github.com/JoeMayo/LinqToTwitter/blob/master/New/Demos/Linq2TwitterDemos_WindowsPhone/OAuth.xaml

**Comment by ulpin** [comment]
Thank You for telling me that. Can't believe I did't figure this one out by my own.

But now I'm getting the exact same error message as in [issue14](https://github.com/JoeMayo/LinqToTwitter/issues/14).
I can't find a solution there...
