### ISSUE TITLE
XAML creating textblocks with hyperlinks and other tweet related content

### ISSUE THREAD

**Issue by ulpin** [JoeMayo/LinqToTwitter#54]
Hi,

I'm developing a Windows Phone 8.1 application and now I want to recreate a tweet with all the images, text, user mentions, hyperlinks etc. 

It is easy to put the `status.text` in a XAML text box, but the issue here is how to get the links underlined and working because there is no easy way to mix up hyperlinks and pure text in a single textblock.
This problem is probably more a XAML issue than a L2T but maybe somebody (Joe ;-)) have some experience with this so far. 

My solution would be:
After retrieving the tweet information I would try to recreate something like that 

![image](https://cloud.githubusercontent.com/assets/13366158/14231404/2d3fc1d2-f982-11e5-826d-d349821b98e1.png)

But this would mean a huge amount of c# to create this dynamically at runtime.

Is this really the way to go? 

Cheers,
Chris

**Comment by JoeMayo** [comment]
Hi Chris,

The Status has an Entities and ExtendedEntities (newer) property that gives you that start and end position of each URL. That way, you can manually write the code that shapes the text the way you want.

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by ulpin** [comment]
Yes, Thank You. I've already found this property. I think I can work with that. I am still trying to find a better solution than in my screenshot above. Don't like that very much. I am hoping to achieve something with a `RichEditBox`style element.
