### ISSUE TITLE
LinqToTwitter doesn't work in PCL in Xamarin.Forms for UWP

### ISSUE THREAD

**Issue by HelenMamalaki** [JoeMayo/LinqToTwitter#57]
I know that LinqToTwitter supports UWP and it support Xamarin.Forms, but using the UniversalAuthoriser (which is for UWP) namespace is not available when called from within the PCL in my Xamarin.Forms project. It works if I place the code in the UWP project though, but then I don't have a way of referencing that from the PCL. Any help would be appreciated.
I am using Linq2Twitter v4.x

https://stackoverflow.com/questions/36792374/linqtotwitter-doesnt-work-in-pcl-in-xamarin-forms-for-uwp

**Comment by JoeMayo** [comment]
Today, I pushed the changes to support .NET Standard. As part of that, I added a LinqToTwitter.UWP assembly with UniversalAuthorizer.

Deployed to NuGet (as v5.0.0-beta1):

https://www.nuget.org/packages/linqtotwitter/

Sample Code:

https://github.com/JoeMayo/LinqToTwitter/tree/master/Samples/Xamarin/NetStd

[@JoeMayo](https://twitter.com/JoeMayo)
