### ISSUE TITLE
remove modernhttpclient dependency

### ISSUE THREAD

**Issue by Jagadeesh-Govindaraj** [JoeMayo/LinqToTwitter#59]
look at this issue

https://github.com/jaymedavis/stripe.net/issues/500

**Comment by JoeMayo** [comment]
This was fixed in [LINQ to Twitter v4.2.0](https://github.com/JoeMayo/LinqToTwitter/releases/tag/v4.2.0).

[@JoeMayo](https://twitter.com/JoeMayo)
