### ISSUE TITLE
TwitterContext does not contain a definition for TweetWithMediaAsync 

### ISSUE THREAD

**Issue by dtsob75** [JoeMayo/LinqToTwitter#60]
I am taking over support for a .net mvc web app that uses LinqToTwitter.  I just updated the L2T version to 4.1.0 and I am getting the above error on this line of code:
`Status tweet  = await twitterCtx.TweetWithMediaAsync(message, possiblySensitive, imageBytes);`
I tried to downgrade to 4.0 but I get numerous other errors.  
I am new to working with Twitter, so I am totally lost.  Would you please help me figure out the problem?
Help is appreciated...
Thanks,
JoelWZ

**Comment by JoeMayo** [comment]
Hi JoelWZ,

Here's a demo for doing that. Look at the UploadMultipleImagesAsync method:

https://github.com/JoeMayo/LinqToTwitter/blob/master/Samples/net46/CSharp/ConsoleSamples/StatusDemos.cs

Essentially, you upload the media (from 1 to 4) collect the media IDs that the upload gives you back, and then tweet with the list of media IDs. Twitter will grab the images you uploaded, indexed by media ID an put them in your tweet.

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by dtsob75** [comment]
Joe,

Thanks for the quick reply.  I was able to replace our code with your sample snippet and got past the compile error I was getting.

 

Thanks for your help!!

 

 

Thanks,

 

Joel Zinn

**Comment by JoeMayo** [comment]
Joel,

You're welcome. Thanks for the issue - the docs for this need to be updated.

[@JoeMayo](https://twitter.com/JoeMayo)
