### ISSUE TITLE
How do i set Request Token on PinAuthorizer object

### ISSUE THREAD

**Issue by chidionuekwusi** [JoeMayo/LinqToTwitter#62]
How do i set Request Token on PinAuthorizer object ??. My application has already generated a valid request token , i simply want to complete authorization using PinAuthorizer is that possible ?

**Comment by JoeMayo** [comment]
Here's an example of how to use the PinAuthorizer: https://github.com/JoeMayo/LinqToTwitter/blob/master/Samples/net46/CSharp/ConsoleSamples/Program.cs
