### ISSUE TITLE
Twitter digits

### ISSUE THREAD

**Issue by sohayb** [JoeMayo/LinqToTwitter#63]
Hello,
Do you plan on adding Twitter digits kit support?

**Comment by JoeMayo** [comment]
No plans at this time. Twitter doesn't appear to have a desire to support Microsoft platforms and that makes me unsure of whether it's worth my time to expand the scope of the project.

**Comment by syrakozz** [comment]
+1

**Comment by JoeMayo** [comment]
Here's a discussion I started on the Twitter Developer forums:

https://twittercommunity.com/t/digits-rest-api/68200

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by JoeMayo** [comment]
The response from Twitter is that they don't have REST support yet. LINQ to Twitter uses the public REST API to communicate and the Digits and Fabric capabilities aren't included in that.

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by sohayb** [comment]
Thanks a lot, I guess we have to wait till they support it then.
