### ISSUE TITLE
Twitter connection stops.

### ISSUE THREAD

**Issue by DanGraZisson** [JoeMayo/LinqToTwitter#64]
Hello, I hope this is the right place to post this question/issue.
I'm using LinqToTwitter in a C#/Silverlight application to stream Twitter statuses and DMs, however every few days between 03:40-04:40 in the morning (Norwegian time) the streams stops getting messages from Twitter, both keep alive (empty) messages and tweets.
I'm using the stream API.

`public async Task Stream(CancellationToken token)
        {
            await VerifyUserAccount(token);

            while (!token.IsCancellationRequested)
            {
                Logger.Warn("Beginning of where.");
                await _twitterContext.Streaming.Where(strm => strm.Type == StreamingType.User && strm.AllReplies == true)
                    .StartAsync(async strm =>
                    {
                        try {
                            await HandleTwitterStream(strm);
                        }
                        catch(Exception e)
                        {
                            Logger.Warn(e);
                        }

                        if (token.IsCancellationRequested || _stopStreaming)
                        {
                            strm.CloseStream();
                        }
                    });
                Logger.Warn("End of where.");
            }
        }`

What troubles me is that when the stream "dies" it does not exit the _twitterContext.Streaming.Where clause so I cannot restart the stream, nor know within the program that the stream is down. The only reason I know is because I log all the keep alive messages and when I send a tweet that this program is supposed to pick up it does not reach it at all.

I hope you can help me with a hint on solving this or if not where I might be able to get some help to solve it.

**Comment by JoeMayo** [comment]
Silverlight - I didn't know that would work. :)

You can use the WithCancellation operator, like this:

            await _twitterContext.Streaming.Where(strm => strm.Type == StreamingType.User && strm.AllReplies == true)
                .WithCancellation(token)
                .StartAsync(async strm =>
                {
                    try {
                        await HandleTwitterStream(strm);
                    }
                    catch(Exception e)
                    {
                        Logger.Warn(e);
                    }

                    if (token.IsCancellationRequested || _stopStreaming)
                    {
                        strm.CloseStream();
                    }
                });

Then, you might set a timer every time you HandleTwitterStream(strm) and cancel the stream if the timer expires.

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by DanGraZisson** [comment]
Thank you @JoeMayo, I'll implement it right away and get to testing it!

**Comment by DanGraZisson** [comment]
After many days of testing I have concluded that your suggestion solved the problem.
Thank you very much for your help and for creating this library.
