### ISSUE TITLE
Streaming memory leak.

### ISSUE THREAD

**Issue by RichardMosley** [JoeMayo/LinqToTwitter#66]
Hello,

I'm having an issue where streaming will cause a memory leak. The problem does not happen right way, only after the stream has been open for some time, normally a few days, will it start to leak memory.  

I had this occur on my local machine and on my server at the same time, even though the server application had been running for several more hours. This makes me think the data Twitter is sending over is somehow responsible.

An ANTS memory profile results can be downloaded from here: http://tinyurl.com/znuy4xn

Here is my code:

```
try
{
    await Task.Run(async () =>
   {
       Streaming stream = await TwitterSteam(trackHashTags, twitterUserIds);                           
       CloseStreamSource.Token.ThrowIfCancellationRequested();
   });                                          
}
catch (TaskCanceledException ex) 
{
    //Do nothing, this was manually canceled.
}
catch (OperationCanceledException ex)
{
    //Do nothing, this was manually canceled.
}
```

```
private async Task<Streaming> TwitterSteam(string trackHashTags, string twitterUserIds)
        {
            var stream = (from strm in TwitterCtx.Streaming.WithCancellation(CloseStreamSource.Token)
                          where strm.Type == StreamingType.Filter &&
                          strm.Track == trackHashTags
                          && strm.Follow == (string.IsNullOrEmpty(twitterUserIds) ? "41553192" : twitterUserIds) // This might be needed for rewtweets.
                          select strm).StartAsync(async strm =>
                         {
                            string message = string.IsNullOrEmpty(strm.Content) ? "Keep-Alive" : strm.Content;

                            if (message == "Keep-Alive")
                            {
                                IsRunning = true;
                            }
                            else
                            {
                                JsonData data = JsonMapper.ToObject(message);
                                Status tweet = new Status(data);
                                LogClient.LogInfo("Received Tweet: " + tweet.Text, null, LogType.Info, null);
                                ConvertToMessage(tweet);
                                IsRunning = true;
                           }
                        }).Result.SingleOrDefault();

            return stream;
        }
```

**Comment by JoeMayo** [comment]
Hi,

I did some profiling on a few different stream configurations and am not seeing the same thing you are. I ran this for 20 tweets between memory snapshots. The snapshots showed that memory initially increased slightly, but decreased after that and stayed relatively steady. Heap size ranged from 935Kb to 1,100 Kb. Even if it was a slow leak, I would have expected some increase after dozens of tweets. I also refactored your code:

                    await Task.Run(async () =>
                    {
                        await TwitterSteam("twitter", null);
                        CloseStreamSource.Token.ThrowIfCancellationRequested();
                    });

The Streaming instance was local to your lambda and unused.

        private static async Task TwitterSteam(string trackHashTags, string twitterUserIds)
        {
            await (from strm in TwitterCtx.Streaming.WithCancellation(CloseStreamSource.Token)
                   where strm.Type == StreamingType.Filter &&
                   strm.Track == trackHashTags
                   && strm.Follow == (string.IsNullOrEmpty(twitterUserIds) ? "41553192" : twitterUserIds) // This might be needed for rewtweets.
                   select strm).StartAsync(async strm =>
                   {
                       string message = string.IsNullOrEmpty(strm.Content) ? "Keep-Alive" : strm.Content;

                       if (message == "Keep-Alive")
                       {
                           IsRunning = true;
                       }
                       else
                       {
                           JsonData data = JsonMapper.ToObject(message);
                           Status tweet = new Status(data);
                           //LogClient.LogInfo("Received Tweet: " + tweet.Text, null, LogType.Info, null);
                           await ConvertToMessage(tweet);
                           IsRunning = true;
                       }
                   });
        }

By awaiting StartAsync, you could eliminate the call to Result.

        static async Task ConvertToMessage(Status tweet)
        {
            await Task.FromResult(true);
        }

I don't know what you have in ConvertToMessage, but I added some dummy code to make sure it wasn't holding on to references.

You might want to comment out the body of StartAsync and see if you still have problems and gradually uncomment until the problem reappears. I'm using Visual Studio 2015 Diagnostics tools - if you give me a small sample program that demonstrates the problem, along with a step by step description using Visual Studio 2015 Diagnostics tools, I can take another look. I also have Stream demos in the source code: https://github.com/JoeMayo/LinqToTwitter/blob/master/Samples/net46/CSharp/ConsoleSamples/StreamDemos.cs

**Comment by RichardMosley** [comment]
Hi Joe,

Thanks for the advice, I've refactored by code to more closely resemble your examples and it has been running without issue for a couple days now. I'll update this forum after its been running for a week or two. 

Thanks,
Richard.
