### ISSUE TITLE
UpdateAccountImageAsync throw exception

### ISSUE THREAD

**Issue by dhanh** [JoeMayo/LinqToTwitter#67]
Hi,

First of all, thank you so much for supporting .NET community with this great library. I can vote this as the best Twitter Client for .NET ever.

And second could you please help me to solve this issue. I got exception when trying to change user profile and background image 
LinqToTwitter.TwitterQueryException : image parameter is missing

Issue happens also in sample project: 

static async Task UpdateAccountImageAsync(TwitterContext twitterCtx)
        {
            byte[] imageBytes = File.ReadAllBytes(@"..\..\Images\200xColor_2.png");

            var user = await twitterCtx.UpdateAccountImageAsync(
                imageBytes, "200xColor_2.png", "png", false);

            if (user != null)
                Console.WriteLine("User Image: " + user.ProfileImageUrl); 
        }

I look forward for your support.

Thanks.

**Comment by JoeMayo** [comment]
HI,

The string specifying the image path looks suspect - it has 4 dots. Maybe set a breakpoint and verify that `imageBytes` has data.

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by dhanh** [comment]
Hi,

Thanks for your fast response. However, I've already checked the code to make sure that file loaded successfully before. I downgraded to version 3.1.2 and it works. Maybe I use this version for this time.

Anyway, thanks for your support.

Regards,

**Comment by winuser** [comment]
I have this issue too on the latest version available (4.1)

Thanks.
