### ISSUE TITLE
calling authorizeasync in a universal app (10074)  causes error "System.Net.Http.HttpRequestException"

### ISSUE THREAD

**Issue by liquidboy** [JoeMayo/LinqToTwitter#7]
Seems like Universal Apps have changed how web authentication broker works, ... Trying to do a simple auth.AuthorizeAsync() throws an exception

Exception: 
"{"Exception of type 'System.Net.Http.HttpRequestException' was thrown."}"

Inner exception:
"{"HttpVersion Http20"}" 

StackTrace : 
   at System.Net.Http.HttpHandlerToFilter.ConvertResponse(HttpResponseMessage rtResponse)
   at System.Net.Http.HttpHandlerToFilter.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.<SendAsync>d__1.MoveNext()

A windows 8.1 app with the exact same code correctly launches the webauthentication broker webview  ....

**Comment by liquidboy** [comment]
The code i use to authenticate is 


var auth = new LinqToTwitter.WindowsStore.WindowsStoreAuthorizer
            {
                CredentialStore = new LinqToTwitter.InMemoryCredentialStore
                {
                    ConsumerKey = "[MY Consumer Key]",
                    ConsumerSecret = "[My Consumer Secret]"
                },
                SupportsCompression = true,
                Callback = "[my callback uri]"
            };

            await auth.AuthorizeAsync();

**Comment by JoeMayo** [comment]
Thanks for the issue. I'll need to review for compatibility with Windows 10 and will probably need a new authorizer.

**Comment by liquidboy** [comment]
Hi Joe,

A person on Twitter informed me that " System.Net.Http and System.Net.Http.Headers namespace might not be available in future versions of Windows for use by Windows Store apps"

And indeed, if I use "Windows.Web.Http.HttpClient" everything works as expected... 

Sounds like considerable effort for your library to use either windows.web.http / system.net.http ...


link to article : https://msdn.microsoft.com/en-us/library/windows/apps/xaml/hh781239.aspx

**Comment by JoeMayo** [comment]
Here's a link to the @liquidboy fork with a version that works in Windows 10:

https://github.com/liquidboy/LinqToTwitter

I'd like to do a cross-platform implementation. I think I'll need to re-structure the LINQ to Twitter solution. It will probably require multiple projects for platform/version that use a combination of shared libraries for common and platform-specific functionality. it can take the same approach as the @liquidboy fork, implementing a platform-specific ITwitterExecute implementation. That's my current thought pattern and any advice and/or recommendations are welcome.

**Comment by liquidboy** [comment]
it's a good approach, I've been investigating wanting to use LinqToTwitter in a iOS/Android app via Xamarin ...  And on those platforms I would rather use their optimized networking stacks, rather than the Xamarin networking stack..

This article is a good indicator for the approach I would take, with using ModernHttpClient  http://arteksoftware.com/resilient-network-services-with-xamarin/

So I can see myself implementing ITwitterExecute using the ModernHttpClient for iOS/Android and keeping Windows.Web.Http for Modern and System.Net.Http for desktop classic :)

**Comment by JoeMayo** [comment]
I just checked in initial support for UWP. @liquidboy fork helped and the design worked out like I wanted. More to do.

**Comment by JoeMayo** [comment]
Deployed new NuGet package for LINQ to Twitter v4 Beta 1, with UAP support: http://bit.ly/1S63PkR

**Comment by JoeMayo** [comment]
LINQ to Twitter v4.0 released and covers UWP support: https://github.com/JoeMayo/LinqToTwitter/releases/tag/v4.0.0
