### ISSUE TITLE
"Could not authenticate you" using specific search query

### ISSUE THREAD

**Issue by jooooel** [JoeMayo/LinqToTwitter#74]
Hi,
I'm getting the following error when doing a search query:

`ErrorCode: 32. ErrorMessage: Could not authenticate you. - Please visit the LINQ to Twitter FAQ (at the HelpLink) for help on resolving this error. ---> LinqToTwitter.TwitterQueryException: Could not authenticate you. - Please visit the LINQ to Twitter FAQ (at the HelpLink) for help on resolving this error.`

The search query I'm using is the following:
**@ニュース OR to:@ニュース**

My guess is that is has something to do with the generated signature and the Japanese characters? Other similar search queries like "@apple OR to:@apple" work fine.  I would have loved to debug and find the error myself, but unfortunately it seems a bit to complex for me to dive into right now :(. I hope that this will give you enough information to understand what the problem is?

**Steps to reproduce:**
1. Setup credentials for Single User auth
2. In SearchDemos.cs, change the searchString to "@ニュース OR to:@ニュース"
3. Run the **ConsoleSamples** project
4. Select number 3, Single User
5. Select C, Search Demos
6. Select 0, Search

**Comment by JoeMayo** [comment]
This is fixed and I'm planning on including it in a release early this week.

**Comment by JoeMayo** [comment]
This was fixed in [LINQ to Twitter v4.2.0](https://github.com/JoeMayo/LinqToTwitter/releases/tag/v4.2.0).

[@JoeMayo](https://twitter.com/JoeMayo)
