### ISSUE TITLE
The asynchronous action method 'Begin' returns a Task, which cannot be executed synchronously.

### ISSUE THREAD

**Issue by dtsob75** [JoeMayo/LinqToTwitter#75]
I inherited an MVC web app to support and it is running the twitter post using the async controller.  I am having issues because our security routing handler is throwing the above error.  Has anyone experienced this issue?  Is it required to use the async controller?
I am not sure where to event start....

**Comment by JoeMayo** [comment]
Hi,

LINQ to Twitter is async, so you develop with it like other async libraries. The source code has demos:

https://github.com/JoeMayo/LinqToTwitter/tree/master/Samples/net46/CSharp/AspNetSamples

The Security section of the Wiki has explanations of OAuth and there's a discussion on MVC in there too:

https://github.com/JoeMayo/LinqToTwitter/wiki/Securing-Your-Applications

You might also want to upgrade to the latest version on NuGet.

[@JoeMayo](https://twitter.com/JoeMayo)
