### ISSUE TITLE
Null reference at: CredentialStore = new SessionStateCredentialStore() 

### ISSUE THREAD

**Issue by kllr** [JoeMayo/LinqToTwitter#76]
My application should retrieve messages for multiple credentials, so I am trying to fill a SessionStateCredentialStore with values from my database, create a context and search messages..

This is happening inside a FluentScheduler class, because it has to run every x minutes.

The class
------------
 public class MessageCollectionJob: IJob, IRegisteredObject.......

inside the class i have a function which contains the following. 
All values aren't null....
The program gives System.NullReferenceException at the creation of the CredentialStore.

  var auth = new AspNetAuthorizer
            {
                **CredentialStore = new SessionStateCredentialStore()**
                {
                    ConsumerKey = ConfigurationManager.AppSettings["consumerKey"],
                    ConsumerSecret = ConfigurationManager.AppSettings["consumerSecret"],
                    OAuthToken = myToken.OAuthToken,
                    OAuthTokenSecret = myToken.OAuthTokenSecret
                }
            };

Error details
-------------
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=De objectverwijzing is niet op een exemplaar van een object ingesteld.
  Source=LinqToTwitter.AspNet
  StackTrace:
       bij LinqToTwitter.SessionStateCredentialStore..ctor()
       bij blabla.MessageCollectionJob.<TwitterSearchTweets>d__6.MoveNext()

**The strange thing is that when i call the same code using a button on my screen from a mvc project, it works fine?!!?**

Anybody got an idea what is going wrong?

Thanks very much!

**Comment by JoeMayo** [comment]
This is normally caused by the server recycling the application, causing session state to clear out. Make sure you have your Web.config setting session state to StateServer or database.

**Comment by kllr** [comment]
Hi Joe,
Thanks for your quick reply!


I added the following to my Web.config: Do i need to do more than that? I doesn't give any errors but the NullReferenceException still occurs. (do i need to create tables in my azure db or something?)

I<sessionState  mode="SQLServer" sqlConnectionString="Server=tcp:XXXXXX.database.windows.net,1433;Initial Catalog=BlaBla;Persist Security Info=False;User ID=XXXXXX;Password=XXXXXX;Trusted_Connection=False;Encrypt=True;"    cookieless="false"    timeout="20"    allowCustomSqlDatabase="true"  />

Is there also another way to make a TwitterContext with the credentials if the constructor keeps failing over here?
Kind regards
Alex

**Comment by JoeMayo** [comment]
Yes, SQL state store has tables - there's a script you need to run: https://support.microsoft.com/en-us/kb/317604

You could also use an InMemoryCredentialStore and make sure you populate credentials manually each time. You could also implement ICredentialStore for your own custom purposes.
