### ISSUE TITLE
Error occurs in  await authorizer.AuthorizeAsync()- Callback required

### ISSUE THREAD

**Issue by Englbach** [JoeMayo/LinqToTwitter#77]
var authorizer = new UniversalAuthorizer
            {
                CredentialStore = new InMemoryCredentialStore
                {
                    ConsumerKey = ComsumerKey,
                    ConsumerSecret = ConsumerSecret,
                }
            };
            await authorizer.AuthorizeAsync();

![untitled](https://cloud.githubusercontent.com/assets/11801842/19406689/e61c38f4-92b4-11e6-94f2-de51bdf3d63f.png)

Error occurs in  await authorizer.AuthorizeAsync();.. I'm coding login page and get home timeline

**Comment by JoeMayo** [comment]
Are you still seeing this? Did you try the UWP sample in the source code - it's working, so I'm not sure how to reproduce what you're seeing.
