### ISSUE TITLE
Review LinqToTwitter readme page

### ISSUE THREAD

**Issue by MNF** [JoeMayo/LinqToTwitter#78]
It looks that https://github.com/JoeMayo/LinqToTwitter readme page was 
 not updated after move from the  codeplex. It has couple references to Download page, as well as documentation link. 
Please update to reflect github.

**Comment by claudiobernasconi** [comment]
@MNF I was trying to help and looked for readme pages that are not up to date. Unfortunately, I could not find any page that has dead links or something like that. Could you give some specific examples? I would be willing to help out. Otherwise, I think that this issue can be closed.

**Comment by MNF** [comment]
@claudiobernasconi, it looks ok now
