### ISSUE TITLE
LinqtoTwitter memory leak issue

### ISSUE THREAD

**Issue by Stormcloak** [JoeMayo/LinqToTwitter#79]
Hello,
I have a problem that streaming feature causes memory leak. This issue has occured in last few days. Memory is raising top level and application is throwing outofmemory exception. Before last few days, everything was normal. 
I suspected my code and I tried to run streaming feature from LinqToTwitter console sample. But this console application threw outofmemory exception,too. I took a screenshot from console application. 

![outofexception](https://cloud.githubusercontent.com/assets/23010894/19625589/71c55f7c-9925-11e6-92e7-805720654ebc.PNG)

**Comment by TheSylence** [comment]
Same issue here. It started the day [DynDNS was attacked](http://thenextweb.com/security/2016/10/21/massive-ddos-attack-dyn-dns-causing-havoc-online/). Don't know if this is just a coincidence or if something broke on that day. Everything worked fine before.

**Comment by Stormcloak** [comment]
The problem is solved. I guess, Twitter api was source of the problem.

**Comment by JoeMayo** [comment]
Thanks for the update. I've seen folks encounter memory leak issues. It's easy to do if you hold onto references too long. e.g. TwitterContext instance or callback references. Also, if there's not a lot of activity, GC might take longer to kick in and clean up unused references.
