### ISSUE TITLE
.net 4.0 video upload

### ISSUE THREAD

**Issue by zkutch** [JoeMayo/LinqToTwitter#81]
Hi JoeMayo
I am working on .net 4.0 and there cannot find method UploadMediaAsync for context.
How can I upload video?

Thanks beforehand.

Regards.

**Comment by claudiobernasconi** [comment]
Hi @zkutch 

I tried to setup a project targeting the .NET 4.0 framework. When I try to install LinqToTwitter using NuGet I get the following error message (using the latest Visual Studio 2017):

> Could not install package 'linqtotwitter 4.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework.

A quick look at the [NuGet page](https://www.nuget.org/packages/linqtotwitter) of LinqToTwitter reveals that .NET 4.5 is listed as a dependency.

Installing LinqToTwitter using a project targeting the .NET 4.5 framework works perfectly fine for me.

To upload a video (or image), you can use the UploadMediaAsync method which is described in more detail on the [Wiki](https://github.com/JoeMayo/LinqToTwitter/wiki/Uploading-And-Tweeting-Media)

I do not understand how you were able to install LinqToTwitter targeting the .NET 4.0 framework. I suggest upgrading the project to use .NET 4.5. If that is not possible, I do not see how you could make use of LinqToTwitter to solve your problem.

I hope this helps.

**Comment by zkutch** [comment]
Hi @claudiobernasconi 
Thanks for reply.
I tried LinqToTwitter in vs 2010 and had success only with image upload with .net 4.0 on visual basic.
With 4.5 in vs 2010 I made video upload also.
I must say, that I use LinqToTwitter as black box, without looking inside, so, may be it is way to modify it to work with video also in net 4.0.
Thank you one more time for your attention
