### ISSUE TITLE
Include in Twitter search query: -filter:retweets -filter:replies -filter:links -filter:images -filter:videos

### ISSUE THREAD

**Issue by aspmaker** [JoeMayo/LinqToTwitter#82]
Hello everyone.
i want to search some words in twitter with;
 **-filter:retweets -filter:replies -filter:links -filter:images -filter:videos**

but when i did query with this filters, i get this error;
 **Additional information: Could not authenticate you.**

when i try this method of query in twitter or twitter API console i give best results. what must i do for filter query with LinqToTwitter  library?

my example code :
```
var myFilter= "-filter:retweets -filter:replies -filter:links -filter:images -filter:videos";
var myStr = "Dogs " + myFilter;
myStr = Uri.EscapeDataString(myStr);
// if i don't use escape i take error
//if i use it result not change. retweet always include the search result.

         var searchResponse =
                await
                (from search in _twitterContext.Search
                 where search.Type == SearchType.Search &&
                       search.Query == myStr &&
                       search.ResultType == ResultType.Recent &&
                       search.Count == 100
                 select search)
                .SingleOrDefaultAsync();
```

**Comment by glenr4** [comment]
You need to authenticate first, this works for me. You need to get a ConsumerKey and ConsumerSecret using your own Twitter account.

`// Authenticate
				var auth = new ApplicationOnlyAuthorizer() {
					CredentialStore = new InMemoryCredentialStore {
						ConsumerKey = "insertYourKey",
						ConsumerSecret = "insertYourSecret",
					}
				};
				await auth.AuthorizeAsync();

				var _twitterContext = new TwitterContext(auth);`
