### ISSUE TITLE
Extended Tweet User Mentions Missing

### ISSUE THREAD

**Issue by jimparslow** [JoeMayo/LinqToTwitter#85]
Hi,

Using the following code I am getting media in the extended tweet properties, but user mentions are always null. However, userMentions are populated on the standard tweet properties.

Is this expected? Should I be looking in both places?

```
                var searchResponse =
                    await (from search in TwitterContext.Search
                           where search.Type == SearchType.Search &&
                                 search.Query == TwitterSearchString &&
                                 search.SinceID == sinceId && 
                                 search.TweetMode == TweetMode.Extended
                           select search)
                              .SingleOrDefaultAsync();
```

**Comment by JoeMayo** [comment]
Hi @jimparslow,

The extended entities are for media objects. Here's the Twitter docs on that:

https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/extended-entities-object

I remember when adding this, the documentation didn't seem as clear as it does today on what should appear in extended entities, so I added a place for everything, just in case. I'm still waiting and watching to see if this changes.

You should continue to use the normal Entities property for other entity types.

[@JoeMayo](https://twitter.com/JoeMayo)

**Comment by JoeMayo** [comment]
Closing - Just revisited this and the documentation indicates what we assumed:

> No other entity types, such as hashtags and links, are included in the extended_entities section. The media object in the extended_entities section is identical in structure to the one included in the entities section.
