### ISSUE TITLE
AnimatedGif unsupported since 4.2.0

### ISSUE THREAD

**Issue by ErikStammes** [JoeMayo/LinqToTwitter#89]
Hi there,

Ever since upgrading to 4.2.0-beta1 I am unable to post tweets with Animated GIFs attached, this also happens in 4.2.0-beta2, but not in 4.1.0.

Am I doing anything wrong or is there another issue?

Thanks.

**Comment by JoeMayo** [comment]
Thanks for trying the beta and reporting the issue.

**Comment by ErikStammes** [comment]
Hi Joe, thanks for confirming the bug. Do you have an ETA for a bugfix?

**Comment by ErikStammes** [comment]
For anyone else running into this issue, if you don't specify a media_category parameter (or string.Empty), animated GIFs are supported :)
