### ISSUE TITLE
Query with Multiple Status Ids

### ISSUE THREAD

**Issue by EmptyCoffin** [JoeMayo/LinqToTwitter#92]
I am trying to think of a way where to include multiple Status Id's in a single query, something along the lines of:

`from tweet in context.Status
where tweet.Type == StatusType.Retweets
                        && tweet.ID == statusId[0] || tweet.ID == statusId[1]  select tweet`

Any thoughts? Trying to limit the number of api calls

**Comment by JoeMayo** [comment]
I don't believe the Twitter API supports that - let me know if I'm mistaken.

**Comment by EmptyCoffin** [comment]
Researching into it this wouldn't reduce the number of api calls
