### ISSUE TITLE
Move dependency on RX- to System.Reactive

### ISSUE THREAD

**Issue by almostEric** [JoeMayo/LinqToTwitter#94]
The Reactive framework has changed package names, would be nice if linqToTwitter used correct one.
Is this still a live project?

**Comment by JoeMayo** [comment]
Thanks for the note. I'm tied up in a couple other projects and will circle back to work on this one when I can.

**Comment by almostEric** [comment]
Hi Joe,

 

Awesome! Thanks for the quick reply

 

Eric

**Comment by kentcb** [comment]
Hmm, this is kinda janky right now:

![image](https://user-images.githubusercontent.com/1901832/32481603-fc03115e-c3e3-11e7-8fd7-360891fa208a.png)

So you get the right packages when building for netstandard, but the wrong ones when you add to a platform project.

**Comment by JoeMayo** [comment]
Today, I pushed the changes to support .NET Standard. As part of that, I ensured that the new project references the System.Reactive packages.

Deployed to NuGet (as v5.0.0-beta1):

https://www.nuget.org/packages/linqtotwitter/

[@JoeMayo](https://twitter.com/JoeMayo)
