### ISSUE TITLE
ReplyAsync doesn't work

### ISSUE THREAD

**Issue by srt0422** [JoeMayo/LinqToTwitter#95]
Here's a code snippet:

`this.twitterContext.ReplyAsync(id, comment)`

This creates a new tweet, but it doesn't reply to the tweet given by "id".

Is there a workaround?

**Comment by srt0422** [comment]
bump

**Comment by JoeMayo** [comment]
Sorry, I've been tied up and don't know when I'll have a chance to look at this. Did you try the latest Beta pre-release?

**Comment by srt0422** [comment]
I haven't.  I'll give that a try.  are you open to a pull request if I can
fix it myself?

**Comment by JoeMayo** [comment]
Yes, pull requests are welcome - thanks.

**Comment by JoeMayo** [comment]
Are you prefixing the tweet with the @UserName of the person you're replying to?

**Comment by srt0422** [comment]
no

**Comment by JoeMayo** [comment]
That's why - you need to add the @UserName prefix to the tweet.

**Comment by srt0422** [comment]
Thanks.  I'll try that out.
