### ISSUE TITLE
Count is ignored when fetching FriendshipType.FollowersList

### ISSUE THREAD

**Issue by ricardopieper** [JoeMayo/LinqToTwitter#96]
Hey Joe,

Before introducing the problem, thanks for building this library. Makes everything much easier.

I haven't done any debugging yet nor tried to fix it myself, and I don't know if that's by design or if Twitter REST API doesn't support this.

I tried using the sample provided in the method `FollowersListAsync` here: https://github.com/JoeMayo/LinqToTwitter/blob/master/Samples/net46/CSharp/ConsoleSamples/FriendshipDemos.cs. It worked fine, but I want to fetch more followers in a single HTTP request, or else I won't be able to fetch the complete list of followers of a page if it's large enough (300+ followers).

I tried setting the Count property just like in the method ShowFollowerIDsAsync, which works fine: setting Count = 500 brings 500 followers. 

However, when using the same strategy on FollowersListAsync (or whenever using  riendshipType.FollowersList), it keeps returning 20 followers per cursor only, doesn't matter how big Count is. Having 15 requests for each time window, I can only fetch 300 users using this method. It would be nice if I was able to get IDs and screen names at the same time.

I haven't had the time to investigate this, but I wonder what you have in mind. Is it a limitation on Twitter's end? If that's a bug, maybe it's simple enough that I can send a pull request.

**Comment by JoeMayo** [comment]
Sorry, I'm very tied up right now and don't know when I'll have the chance to look closer. If Count is a parameter on the Twitter API endpoint, then L2T should support it.

**Comment by ricardopieper** [comment]
No problem, I figured it out.

According to the documentation for /followers/list.json, the count parameter is "The number of users to return per page, up to a maximum of 200. Defaults to 20".

It turns out that if you exceed the 200 max count, it just defaults to 20 instead of falling back to 200. I was passing 5k.
