### ISSUE TITLE
Re-tweet text gets cut off

### ISSUE THREAD

**Issue by glenr4** [JoeMayo/LinqToTwitter#97]
When I query using this:
```
var tweets = await( from tweet in twitterContext.Status
				where tweet.Type == StatusType.User 
                                     && tweet.ScreenName == screenName 
                                select tweet
				).ToListAsync();
```
If there are re-tweets in the results, they get prefixed with "RT" then the user name, then the message but the Text property gets truncated to 140 characters even though extra characters are inserted into the Text pushing it beyond 140.

I found that I have to first check to see if: tweets[i].RetweetedStatus.Text is not null, if not null then I get the full tweet from there. If it is null, then use tweets[i].Text.

**Comment by JoeMayo** [comment]
Does my response to this issue help?: https://github.com/JoeMayo/LinqToTwitter/issues/100
