### ISSUE TITLE
Get email address

### ISSUE THREAD

**Issue by Vermes** [JoeMayo/LinqToTwitter#98]
Hi.
After many tests I've came here for some help from you guys... I can't get the user email address even if the app is configured to request email address. See my code:

                var UserID = ulong.Parse(loginInfo.ExternalIdentity.Claims.Where(n => n.Type == "urn:twitter:userid").Single().Value);
                var ac = loginInfo.ExternalIdentity.Claims.Where(n => n.Type == "AccessToken").Single().Value;
                var acs = loginInfo.ExternalIdentity.Claims.Where(n => n.Type == "AccessTokenSecret").Single().Value;

                var auth = new SingleUserAuthorizer
                {
                    CredentialStore = new SingleUserInMemoryCredentialStore
                    {
                        ConsumerKey = BL.getData.ConfigValue("Twitter_consumerKey"),
                        ConsumerSecret = BL.getData.ConfigValue("Twitter_consumerSecret"),
                        UserID = UserID,
                        AccessToken = ac.ToString(),
                        AccessTokenSecret = acs.ToString(),
                        ScreenName = loginInfo.DefaultUserName
                    }
                };
                await auth.AuthorizeAsync();
                var twitterCtx = new TwitterContext(auth);

                var verifyResponse =
                    await
                        (from acct in twitterCtx.Account
                         where (acct.Type == LinqToTwitter.AccountType.VerifyCredentials) && (acct.IncludeEmail == true)
                         select acct)
                        .SingleOrDefaultAsync();

                if (verifyResponse != null && verifyResponse.User != null)
                {
                    LinqToTwitter.User twitterUser = verifyResponse.User;
                    loginInfo.Email = twitterUser.Email;
                }
                    var verifyResponse2 =
                        await (from acct in twitterCtx.User
                        where (acct.Type == LinqToTwitter.UserType.Show) && (acct.UserID == UserID)
                               select acct).SingleOrDefaultAsync();
            }

**Comment by JoeMayo** [comment]
Can you hit a breakpoint and look at twitterCtx.RawResult? This will have the User object and you'll be able to see if Twitter actually sent the email.

**Comment by Vermes** [comment]
"{\"id\":892486963829499908,\"id_str\":\"892486963829499908\",\"name\":\"A B\",\"screen_name\":\"GZielono\",\"location\":\"\",\"description\":\"\",\"url\":null,\"entities\":{\"description\":{\"urls\":[]}},\"protected\":false,\"followers_count\":0,\"friends_count\":0,\"listed_count\":0,\"created_at\":\"Thu Jul 27 08:20:12 +0000 2017\",\"favourites_count\":0,\"utc_offset\":null,\"time_zone\":null,\"geo_enabled\":false,\"verified\":false,\"statuses_count\":0,\"lang\":\"pl\",\"contributors_enabled\":false,\"is_translator\":false,\"is_translation_enabled\":false,\"profile_background_color\":\"F5F8FA\",\"profile_background_image_url\":null,\"profile_background_image_url_https\":null,\"profile_background_tile\":false,\"profile_image_url\":\"http:\\/\\/abs.twimg.com\\/sticky\\/default_profile_images\\/default_profile_normal.png\",\"profile_image_url_https\":\"https:\\/\\/abs.twimg.com\\/sticky\\/default_profile_images\\/default_profile_normal.png\",\"profile_link_color\":\"1DA1F2\",\"profile_sidebar_border_color\":\"C0DEED\",\"profile_sidebar_fill_color\":\"DDEEF6\",\"profile_text_color\":\"333333\",\"profile_use_background_image\":true,\"has_extended_profile\":false,\"default_profile\":true,\"default_profile_image\":true,\"following\":false,\"follow_request_sent\":false,\"notifications\":false,\"translator_type\":\"none\"}"

**Comment by Vermes** [comment]
There is no email.  I've tried to add: auth.Parameters.Add("include_email", "true"); but nothing changed

**Comment by Vermes** [comment]
I've set the breakpoint after
` var verifyResponse =
                    await
                        (from acct in twitterCtx.Account
                         where (acct.Type == LinqToTwitter.AccountType.VerifyCredentials) && (acct.IncludeEmail == true)
                         select acct)
                        .SingleOrDefaultAsync();`

**Comment by JoeMayo** [comment]
Twitter didn't send the email address, so there isn't a way for LINQ to Twitter to display it. If you load Fiddler, you can see that ?include_email=true is being sent in the URL. Maybe visit the [Verify Credentials ](https://dev.twitter.com/rest/reference/get/account/verify_credentials) API page and review what they say about setting up email.
